/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.block.BlockSlab
 *  net.minecraft.entity.player.EntityPlayer
 *  net.minecraft.init.Blocks
 *  net.minecraft.init.Items
 *  net.minecraft.item.Item
 *  net.minecraft.item.ItemStack
 *  net.minecraft.world.World
 */
package com.emoniph.witchery;

import com.emoniph.witchery.Witchery;
import com.emoniph.witchery.WitcheryFluids;
import com.emoniph.witchery.brewing.ItemBrew;
import com.emoniph.witchery.brewing.ItemBrewBucket;
import com.emoniph.witchery.common.ExtendedPlayer;
import com.emoniph.witchery.item.ItemArthana;
import com.emoniph.witchery.item.ItemBiomeNote;
import com.emoniph.witchery.item.ItemBoline;
import com.emoniph.witchery.item.ItemBook;
import com.emoniph.witchery.item.ItemBrewBag;
import com.emoniph.witchery.item.ItemBrewEndlessWater;
import com.emoniph.witchery.item.ItemBrewFuel;
import com.emoniph.witchery.item.ItemBucketSpirit;
import com.emoniph.witchery.item.ItemCaneSword;
import com.emoniph.witchery.item.ItemChalk;
import com.emoniph.witchery.item.ItemCircleTalisman;
import com.emoniph.witchery.item.ItemCoffin;
import com.emoniph.witchery.item.ItemDeathsClothes;
import com.emoniph.witchery.item.ItemDeathsHand;
import com.emoniph.witchery.item.ItemDiviner;
import com.emoniph.witchery.item.ItemDuplicationStaff;
import com.emoniph.witchery.item.ItemEarmuffs;
import com.emoniph.witchery.item.ItemEntityLocator;
import com.emoniph.witchery.item.ItemGeneral;
import com.emoniph.witchery.item.ItemGlassGoblet;
import com.emoniph.witchery.item.ItemGoblinClothes;
import com.emoniph.witchery.item.ItemHandBow;
import com.emoniph.witchery.item.ItemHornOfTheHunt;
import com.emoniph.witchery.item.ItemHunterClothes;
import com.emoniph.witchery.item.ItemHuntsmanSpear;
import com.emoniph.witchery.item.ItemKobolditePickaxe;
import com.emoniph.witchery.item.ItemLeonardsUrn;
import com.emoniph.witchery.item.ItemMarkupBook;
import com.emoniph.witchery.item.ItemMirror;
import com.emoniph.witchery.item.ItemMoonCharm;
import com.emoniph.witchery.item.ItemMutator;
import com.emoniph.witchery.item.ItemMysticBranch;
import com.emoniph.witchery.item.ItemParasyticLouse;
import com.emoniph.witchery.item.ItemPolynesiaCharm;
import com.emoniph.witchery.item.ItemPoppet;
import com.emoniph.witchery.item.ItemPoppetShelfCompass;
import com.emoniph.witchery.item.ItemSilverSword;
import com.emoniph.witchery.item.ItemSpectralStone;
import com.emoniph.witchery.item.ItemStew;
import com.emoniph.witchery.item.ItemSunGrenade;
import com.emoniph.witchery.item.ItemTaglockKit;
import com.emoniph.witchery.item.ItemVampireClothes;
import com.emoniph.witchery.item.ItemVanillaPotion;
import com.emoniph.witchery.item.ItemWitchHand;
import com.emoniph.witchery.item.ItemWitchSeeds;
import com.emoniph.witchery.item.ItemWitchSlab;
import com.emoniph.witchery.item.ItemWitchesClothes;
import com.emoniph.witchery.item.ItemWolfToken;
import net.minecraft.block.BlockSlab;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.world.World;

public final class WitcheryItems {
    public final ItemGeneral GENERIC = (ItemGeneral)new ItemGeneral().func_77655_b("witchery:ingredient").func_111206_d("witchery:ingredient");
    public final ItemTaglockKit TAGLOCK_KIT = (ItemTaglockKit)new ItemTaglockKit().func_77655_b("witchery:taglockkit").func_111206_d("witchery:taglockKit");
    public final ItemPoppet POPPET = (ItemPoppet)new ItemPoppet().func_77655_b("witchery:poppet").func_111206_d("witchery:poppet");
    public final ItemVanillaPotion POTIONS = (ItemVanillaPotion)new ItemVanillaPotion().func_77655_b("witchery:potion").func_111206_d("potion");
    public final Item SLAB_SINGLE;
    public final Item SLAB_DOUBLE;
    public final Item PERPERTUAL_ICE_SLAB_SINGLE;
    public final Item PERPERTUAL_ICE_SLAB_DOUBLE;
    public final Item SNOW_SLAB_SINGLE;
    public final Item SNOW_SLAB_DOUBLE;
    public final Item COFFIN;
    public final Item STEW;
    public final Item STEW_RAW;
    public final Item MIRROR;
    public final Item CHALK_RITUAL;
    public final Item CHALK_OTHERWHERE;
    public final Item CHALK_INFERNAL;
    public final Item CHALK_GOLDEN;
    public final Item BOLINE;
    public final Item ARTHANA;
    public final Item HUNTSMANS_SPEAR;
    public final Item CROSSBOW_PISTOL;
    public final ItemDeathsHand DEATH_HAND;
    public final Item SILVER_SWORD;
    public final ItemCaneSword CANE_SWORD;
    public final Item WITCH_HAND;
    public final Item CIRCLE_TALISMAN;
    public final Item MYSTIC_BRANCH;
    public final Item DIVINER_WATER;
    public final Item DIVINER_LAVA;
    public final Item POLYNESIA_CHARM;
    public final Item DEVILS_TONGUE_CHARM;
    public final Item MUTATING_SPRIG;
    public final Item PARASYTIC_LOUSE;
    public final Item BREW_BAG;
    public final Item SPECTRAL_STONE;
    public final Item SHELF_COMPASS;
    public final Item KOBOLDITE_PICKAXE;
    public final Item DUP_STAFF;
    public final Item BREW;
    public final Item BREW_FUEL;
    public final Item BREW_ENDLESS_WATER;
    public final Item BIOME_BOOK;
    public final Item BIOME_NOTE;
    public final Item CAULDRON_BOOK;
    public final Item LEONARDS_URN;
    public final Item PLAYER_COMPASS;
    public final Item MOON_CHARM;
    public final Item HORN_OF_THE_HUNT;
    public final Item CREATIVE_WOLF_TOKEN;
    public final ItemGlassGoblet BLOOD_GOBLET;
    public final Item SUN_GRENADE;
    public final Item VAMPIRE_BOOK;
    public final Item DUP_GRENADE;
    public final ItemWitchesClothes WITCH_HAT;
    public final ItemWitchesClothes BABAS_HAT;
    public final ItemWitchesClothes WITCH_ROBES;
    public final ItemWitchesClothes NECROMANCERS_ROBES;
    public final ItemWitchesClothes BITING_BELT;
    public final ItemWitchesClothes BARK_BELT;
    public final ItemWitchesClothes ICY_SLIPPERS;
    public final ItemWitchesClothes RUBY_SLIPPERS;
    public final ItemWitchesClothes SEEPING_SHOES;
    public final ItemHunterClothes HUNTER_HAT;
    public final ItemHunterClothes HUNTER_COAT;
    public final ItemHunterClothes HUNTER_LEGS;
    public final ItemHunterClothes HUNTER_BOOTS;
    public final ItemHunterClothes HUNTER_HAT_SILVERED;
    public final ItemHunterClothes HUNTER_COAT_SILVERED;
    public final ItemHunterClothes HUNTER_LEGS_SILVERED;
    public final ItemHunterClothes HUNTER_BOOTS_SILVERED;
    public final ItemHunterClothes HUNTER_HAT_GARLICKED;
    public final ItemHunterClothes HUNTER_COAT_GARLICKED;
    public final ItemHunterClothes HUNTER_LEGS_GARLICKED;
    public final ItemHunterClothes HUNTER_BOOTS_GARLICKED;
    public final ItemDeathsClothes DEATH_HOOD;
    public final ItemDeathsClothes DEATH_ROBE;
    public final ItemDeathsClothes DEATH_FEET;
    public final Item MOGS_QUIVER;
    public final Item GULGS_GURDLE;
    public final Item KOBOLDITE_HELM;
    public final Item EARMUFFS;
    public final ItemVampireClothes VAMPIRE_HAT;
    public final ItemVampireClothes VAMPIRE_HELMET;
    public final ItemVampireClothes VAMPIRE_COAT;
    public final ItemVampireClothes VAMPIRE_COAT_FEMALE;
    public final ItemVampireClothes VAMPIRE_COAT_CHAIN;
    public final ItemVampireClothes VAMPIRE_COAT_FEMALE_CHAIN;
    public final ItemVampireClothes VAMPIRE_LEGS;
    public final ItemVampireClothes VAMPIRE_LEGS_KILT;
    public final ItemVampireClothes VAMPIRE_BOOTS;
    public final Item SEEDS_BELLADONNA;
    public final Item SEEDS_MANDRAKE;
    public final Item SEEDS_ARTICHOKE;
    public final Item SEEDS_SNOWBELL;
    public final Item SEEDS_WORMWOOD;
    public final Item SEEDS_MINDRAKE;
    public final Item SEEDS_WOLFSBANE;
    public final Item SEEDS_GARLIC;
    public final Item BUCKET_FLOWINGSPIRIT;
    public final Item BUCKET_HOLLOWTEARS;
    public final Item BUCKET_BREW;

    public WitcheryItems() {
        this.SLAB_SINGLE = new ItemWitchSlab((BlockSlab)Witchery.Blocks.WOOD_SLAB_SINGLE, (BlockSlab)Witchery.Blocks.WOOD_SLAB_SINGLE, (BlockSlab)Witchery.Blocks.WOOD_SLAB_DOUBLE).func_77655_b("witchery:witchwoodslab");
        this.SLAB_DOUBLE = new ItemWitchSlab((BlockSlab)Witchery.Blocks.WOOD_SLAB_DOUBLE, (BlockSlab)Witchery.Blocks.WOOD_SLAB_SINGLE, (BlockSlab)Witchery.Blocks.WOOD_SLAB_DOUBLE).func_77655_b("witchery:witchwooddoubleslab");
        this.PERPERTUAL_ICE_SLAB_SINGLE = new ItemWitchSlab((BlockSlab)Witchery.Blocks.PERPETUAL_ICE_SLAB_SINGLE, (BlockSlab)Witchery.Blocks.PERPETUAL_ICE_SLAB_SINGLE, (BlockSlab)Witchery.Blocks.PERPETUAL_ICE_SLAB_DOUBLE).func_77655_b("witchery:iceslab");
        this.PERPERTUAL_ICE_SLAB_DOUBLE = new ItemWitchSlab((BlockSlab)Witchery.Blocks.PERPETUAL_ICE_SLAB_DOUBLE, (BlockSlab)Witchery.Blocks.PERPETUAL_ICE_SLAB_SINGLE, (BlockSlab)Witchery.Blocks.PERPETUAL_ICE_SLAB_DOUBLE).func_77655_b("witchery:icedoubleslab");
        this.SNOW_SLAB_SINGLE = new ItemWitchSlab((BlockSlab)Witchery.Blocks.SNOW_SLAB_SINGLE, (BlockSlab)Witchery.Blocks.SNOW_SLAB_SINGLE, (BlockSlab)Witchery.Blocks.SNOW_SLAB_DOUBLE).func_77655_b("witchery:snowslab");
        this.SNOW_SLAB_DOUBLE = new ItemWitchSlab((BlockSlab)Witchery.Blocks.SNOW_SLAB_DOUBLE, (BlockSlab)Witchery.Blocks.SNOW_SLAB_SINGLE, (BlockSlab)Witchery.Blocks.SNOW_SLAB_DOUBLE).func_77655_b("witchery:snowdoubleslab");
        this.COFFIN = new ItemCoffin().func_77655_b("witchery:coffin").func_111206_d("witchery:coffin");
        this.STEW = new ItemStew(12, 1.0f).func_77655_b("witchery:stew").func_111206_d("witchery:stew");
        this.STEW_RAW = new ItemStew(1, 0.1f).func_77655_b("witchery:stewraw").func_111206_d("witchery:stewraw");
        this.MIRROR = new ItemMirror().func_77655_b("witchery:mirror").func_111206_d("witchery:mirror");
        this.CHALK_RITUAL = new ItemChalk(Witchery.Blocks.GLYPH_RITUAL).func_77655_b("witchery:chalkritual").func_111206_d("witchery:chalkRitual");
        this.CHALK_OTHERWHERE = new ItemChalk(Witchery.Blocks.GLYPH_OTHERWHERE).func_77655_b("witchery:chalkotherwhere").func_111206_d("witchery:chalkOtherwhere");
        this.CHALK_INFERNAL = new ItemChalk(Witchery.Blocks.GLYPH_INFERNAL).func_77655_b("witchery:chalkinfernal").func_111206_d("witchery:chalkInfernal");
        this.CHALK_GOLDEN = new ItemChalk(Witchery.Blocks.CIRCLE).func_77655_b("witchery:chalkheart").func_111206_d("witchery:chalkHeart");
        this.BOLINE = new ItemBoline().func_77655_b("witchery:boline").func_111206_d("witchery:boline");
        this.ARTHANA = new ItemArthana().func_77655_b("witchery:arthana").func_111206_d("witchery:arthana");
        this.HUNTSMANS_SPEAR = new ItemHuntsmanSpear().func_77655_b("witchery:huntsmanspear").func_111206_d("witchery:huntsmanspear");
        this.CROSSBOW_PISTOL = new ItemHandBow().func_77655_b("witchery:handbow").func_111206_d("witchery:handbow");
        this.DEATH_HAND = (ItemDeathsHand)new ItemDeathsHand().func_77655_b("witchery:deathshand").func_111206_d("witchery:deathshand");
        this.SILVER_SWORD = new ItemSilverSword().func_77655_b("witchery:silversword").func_111206_d("witchery:silversword");
        this.CANE_SWORD = (ItemCaneSword)new ItemCaneSword().func_77655_b("witchery:canesword").func_111206_d("witchery:canesword");
        this.WITCH_HAND = new ItemWitchHand().func_77655_b("witchery:witchhand").func_111206_d("witchery:witchHand");
        this.CIRCLE_TALISMAN = new ItemCircleTalisman().func_77655_b("witchery:circletalisman").func_111206_d("witchery:circleTalisman");
        this.MYSTIC_BRANCH = new ItemMysticBranch().func_77655_b("witchery:mysticbranch").func_111206_d("witchery:mysticbranch");
        this.DIVINER_WATER = new ItemDiviner(Blocks.field_150355_j).func_77655_b("witchery:divinerwater").func_111206_d("witchery:divinerWater");
        this.DIVINER_LAVA = new ItemDiviner(Blocks.field_150353_l).func_77655_b("witchery:divinerlava").func_111206_d("witchery:divinerLava");
        this.POLYNESIA_CHARM = new ItemPolynesiaCharm(false).func_77655_b("witchery:polynesiacharm").func_111206_d("witchery:polynesiaCharm");
        this.DEVILS_TONGUE_CHARM = new ItemPolynesiaCharm(true).func_77655_b("witchery:devilstonguecharm").func_111206_d("witchery:devilsTongueCharm");
        this.MUTATING_SPRIG = new ItemMutator().func_77655_b("witchery:mutator").func_111206_d("witchery:mutator");
        this.PARASYTIC_LOUSE = new ItemParasyticLouse().func_77655_b("witchery:louse").func_111206_d("witchery:louse");
        this.BREW_BAG = new ItemBrewBag().func_77655_b("witchery:brewbag").func_111206_d("witchery:brewbag");
        this.SPECTRAL_STONE = new ItemSpectralStone().func_77655_b("witchery:spectralstone").func_111206_d("witchery:witchery.spectralstone");
        this.SHELF_COMPASS = new ItemPoppetShelfCompass().func_77655_b("witchery:shelfcompass").func_111206_d("witchery:shelfcompass");
        this.KOBOLDITE_PICKAXE = new ItemKobolditePickaxe().func_77655_b("witchery:kobolditepickaxe").func_111206_d("witchery:kobolditepickaxe");
        this.DUP_STAFF = new ItemDuplicationStaff().func_77655_b("witchery:dupstaff").func_111206_d("witchery:dupstaff");
        this.BREW = new ItemBrew().func_77655_b("witchery:brewbottle").func_111206_d("witchery:brew_drinkable");
        this.BREW_FUEL = new ItemBrewFuel().func_77655_b("witchery:brew.fuel").func_111206_d("witchery:brew_drinkable");
        this.BREW_ENDLESS_WATER = new ItemBrewEndlessWater().func_77655_b("witchery:brew.water").func_111206_d("witchery:brew_drinkable");
        this.BIOME_BOOK = new ItemBook().func_77655_b("witchery:bookbiomes2").func_111206_d("witchery:biomebook2");
        this.BIOME_NOTE = new ItemBiomeNote().func_77655_b("witchery:biomenote").func_111206_d("witchery:biomenote");
        this.CAULDRON_BOOK = new ItemMarkupBook(7).func_77655_b("witchery:cauldronbook").func_111206_d("witchery:bookcauldron");
        this.LEONARDS_URN = new ItemLeonardsUrn().func_77655_b("witchery:leonardsurn").func_111206_d("witchery:leonardsurn");
        this.PLAYER_COMPASS = new ItemEntityLocator().func_77655_b("witchery:playercompass").func_111206_d("witchery:playercompass");
        this.MOON_CHARM = new ItemMoonCharm().func_77655_b("witchery:mooncharm").func_111206_d("witchery:mooncharm");
        this.HORN_OF_THE_HUNT = new ItemHornOfTheHunt().func_77655_b("witchery:hornofthehunt").func_111206_d("witchery:hornofthehunt");
        this.CREATIVE_WOLF_TOKEN = new ItemWolfToken().func_77655_b("witchery:wolftoken").func_111206_d("witchery:wolftoken");
        this.BLOOD_GOBLET = (ItemGlassGoblet)new ItemGlassGoblet().func_77655_b("witchery:glassgoblet").func_111206_d("witchery:glassgoblet");
        this.SUN_GRENADE = new ItemSunGrenade(0).func_77655_b("witchery:sungrenade").func_111206_d("witchery:sungrenade");
        this.VAMPIRE_BOOK = new ItemMarkupBook(7, new int[]{0, 9}){

            @Override
            public void onBookRead(ItemStack stack, World world, EntityPlayer player) {
                ExtendedPlayer.get(player).increaseVampireLevelCap(stack.func_77960_j() + 1);
            }
        }.func_77655_b("witchery:vampirebook").func_111206_d("witchery:vbook");
        this.DUP_GRENADE = new ItemSunGrenade(1).func_77655_b("witchery:dupgrenade").func_111206_d("witchery:dupgrenade");
        this.WITCH_HAT = (ItemWitchesClothes)new ItemWitchesClothes(0).func_77655_b("witchery:witchhat").func_111206_d("witchery:witchesHat");
        this.BABAS_HAT = (ItemWitchesClothes)new ItemWitchesClothes(0).func_77655_b("witchery:babashat").func_111206_d("witchery:babasHat");
        this.WITCH_ROBES = (ItemWitchesClothes)new ItemWitchesClothes(1).func_77655_b("witchery:witchrobe").func_111206_d("witchery:witchesRobes");
        this.NECROMANCERS_ROBES = (ItemWitchesClothes)new ItemWitchesClothes(1).func_77655_b("witchery:necromancerrobe").func_111206_d("witchery:necromancerRobes");
        this.BITING_BELT = (ItemWitchesClothes)new ItemWitchesClothes(2).func_77655_b("witchery:bitingbelt").func_111206_d("witchery:bitingBelt");
        this.BARK_BELT = (ItemWitchesClothes)new ItemWitchesClothes(2).func_77655_b("witchery:barkbelt").func_111206_d("witchery:barkBelt");
        this.ICY_SLIPPERS = (ItemWitchesClothes)new ItemWitchesClothes(3).func_77655_b("witchery:iceslippers").func_111206_d("witchery:iceSlippers");
        this.RUBY_SLIPPERS = (ItemWitchesClothes)new ItemWitchesClothes(3).func_77655_b("witchery:rubyslippers").func_111206_d("witchery:rubySlippers");
        this.SEEPING_SHOES = (ItemWitchesClothes)new ItemWitchesClothes(3).func_77655_b("witchery:seepingshoes").func_111206_d("witchery:seepingShoes");
        this.HUNTER_HAT = (ItemHunterClothes)new ItemHunterClothes(0, false, false).func_77655_b("witchery:hunterhat").func_111206_d("witchery:hunterhat");
        this.HUNTER_COAT = (ItemHunterClothes)new ItemHunterClothes(1, false, false).func_77655_b("witchery:huntercoat").func_111206_d("witchery:huntercoat");
        this.HUNTER_LEGS = (ItemHunterClothes)new ItemHunterClothes(2, false, false).func_77655_b("witchery:hunterlegs").func_111206_d("witchery:hunterlegs");
        this.HUNTER_BOOTS = (ItemHunterClothes)new ItemHunterClothes(3, false, false).func_77655_b("witchery:hunterboots").func_111206_d("witchery:hunterboots");
        this.HUNTER_HAT_SILVERED = (ItemHunterClothes)new ItemHunterClothes(0, true, false).func_77655_b("witchery:hunterhatsilvered").func_111206_d("witchery:hunterhat");
        this.HUNTER_COAT_SILVERED = (ItemHunterClothes)new ItemHunterClothes(1, true, false).func_77655_b("witchery:huntercoatsilvered").func_111206_d("witchery:huntercoat");
        this.HUNTER_LEGS_SILVERED = (ItemHunterClothes)new ItemHunterClothes(2, true, false).func_77655_b("witchery:hunterlegssilvered").func_111206_d("witchery:hunterlegs");
        this.HUNTER_BOOTS_SILVERED = (ItemHunterClothes)new ItemHunterClothes(3, true, false).func_77655_b("witchery:hunterbootssilvered").func_111206_d("witchery:hunterboots");
        this.HUNTER_HAT_GARLICKED = (ItemHunterClothes)new ItemHunterClothes(0, true, true).func_77655_b("witchery:hunterhatgarlicked").func_111206_d("witchery:hunterhat");
        this.HUNTER_COAT_GARLICKED = (ItemHunterClothes)new ItemHunterClothes(1, true, true).func_77655_b("witchery:huntercoatgarlicked").func_111206_d("witchery:huntercoat");
        this.HUNTER_LEGS_GARLICKED = (ItemHunterClothes)new ItemHunterClothes(2, true, true).func_77655_b("witchery:hunterlegsgarlicked").func_111206_d("witchery:hunterlegs");
        this.HUNTER_BOOTS_GARLICKED = (ItemHunterClothes)new ItemHunterClothes(3, true, true).func_77655_b("witchery:hunterbootsgarlicked").func_111206_d("witchery:hunterboots");
        this.DEATH_HOOD = (ItemDeathsClothes)new ItemDeathsClothes(0).func_77655_b("witchery:deathscowl").func_111206_d("witchery:deathscowl");
        this.DEATH_ROBE = (ItemDeathsClothes)new ItemDeathsClothes(1).func_77655_b("witchery:deathsrobe").func_111206_d("witchery:deathsrobe");
        this.DEATH_FEET = (ItemDeathsClothes)new ItemDeathsClothes(3).func_77655_b("witchery:deathsfeet").func_111206_d("witchery:deathsfeet");
        this.MOGS_QUIVER = new ItemGoblinClothes(1).func_77655_b("witchery:quiverofmog").func_111206_d("witchery:mogquiver");
        this.GULGS_GURDLE = new ItemGoblinClothes(2).func_77655_b("witchery:gurdleofgulg").func_111206_d("witchery:gulggurdle");
        this.KOBOLDITE_HELM = new ItemGoblinClothes(0).func_77655_b("witchery:kobolditehelm").func_111206_d("witchery:kobolditehelm");
        this.EARMUFFS = new ItemEarmuffs(0).func_77655_b("witchery:earmuffs").func_111206_d("witchery:earmuffs");
        this.VAMPIRE_HAT = (ItemVampireClothes)new ItemVampireClothes(0, false, false).func_77655_b("witchery:vampirehat").func_111206_d("witchery:vampirehat");
        this.VAMPIRE_HELMET = (ItemVampireClothes)new ItemVampireClothes(0, false, true).func_77655_b("witchery:vampirehelmet").func_111206_d("witchery:vampirehelmet");
        this.VAMPIRE_COAT = (ItemVampireClothes)new ItemVampireClothes(1, false, false).func_77655_b("witchery:vampirecoat").func_111206_d("witchery:vampirecoat");
        this.VAMPIRE_COAT_FEMALE = (ItemVampireClothes)new ItemVampireClothes(1, true, false).func_77655_b("witchery:vampirecoat_female").func_111206_d("witchery:vampirecoat");
        this.VAMPIRE_COAT_CHAIN = (ItemVampireClothes)new ItemVampireClothes(1, false, true).func_77655_b("witchery:vampirechaincoat").func_111206_d("witchery:vampirechaincoat");
        this.VAMPIRE_COAT_FEMALE_CHAIN = (ItemVampireClothes)new ItemVampireClothes(1, true, true).func_77655_b("witchery:vampirechaincoat_female").func_111206_d("witchery:vampirechaincoat");
        this.VAMPIRE_LEGS = (ItemVampireClothes)new ItemVampireClothes(2, false, false).func_77655_b("witchery:vampirelegs").func_111206_d("witchery:vampirelegs");
        this.VAMPIRE_LEGS_KILT = (ItemVampireClothes)new ItemVampireClothes(2, true, false).func_77655_b("witchery:vampirelegs_kilt").func_111206_d("witchery:vampirelegs_kilt");
        this.VAMPIRE_BOOTS = (ItemVampireClothes)new ItemVampireClothes(3, false, false).func_77655_b("witchery:vampireboots").func_111206_d("witchery:vampireboots");
        this.SEEDS_BELLADONNA = new ItemWitchSeeds(Witchery.Blocks.CROP_BELLADONNA, new ItemStack((Item)this.GENERIC, 1, this.GENERIC.itemBelladonnaFlower.damageValue), Blocks.field_150458_ak, false).func_77655_b("witchery:seedsbelladonna").func_111206_d("witchery:ingredient.seedsBelladonna");
        this.SEEDS_MANDRAKE = new ItemWitchSeeds(Witchery.Blocks.CROP_MANDRAKE, new ItemStack((Item)this.GENERIC, 1, this.GENERIC.itemMandrakeRoot.damageValue), Blocks.field_150458_ak, false).func_77655_b("witchery:seedsmandrake").func_111206_d("witchery:ingredient.seedsMandrake");
        this.SEEDS_ARTICHOKE = new ItemWitchSeeds(Witchery.Blocks.CROP_ARTICHOKE, new ItemStack((Item)this.GENERIC, 1, this.GENERIC.itemArtichoke.damageValue), Blocks.field_150458_ak, true).func_77655_b("witchery:seedsartichoke").func_111206_d("witchery:ingredient.seedsArtichoke");
        this.SEEDS_SNOWBELL = new ItemWitchSeeds(Witchery.Blocks.CROP_SNOWBELL, new ItemStack(Items.field_151126_ay), Blocks.field_150458_ak, false).func_77655_b("witchery:seedssnowbell").func_111206_d("witchery:ingredient.seedsSnowbell");
        this.SEEDS_WORMWOOD = new ItemWitchSeeds(Witchery.Blocks.CROP_WORMWOOD, new ItemStack((Item)this.GENERIC, 1, this.GENERIC.itemWormwood.damageValue), Blocks.field_150458_ak, false).func_77655_b("witchery:seedswormwood").func_111206_d("witchery:ingredient.seedswormwood");
        this.SEEDS_MINDRAKE = new ItemWitchSeeds(Witchery.Blocks.CROP_MINDRAKE, null, Blocks.field_150458_ak, false).func_77655_b("witchery:seedsmindrake").func_111206_d("witchery:ingredient.mindrakebulb");
        this.SEEDS_WOLFSBANE = new ItemWitchSeeds(Witchery.Blocks.CROP_WOLFSBANE, new ItemStack((Item)this.GENERIC, 1, this.GENERIC.itemWolfsbane.damageValue), Blocks.field_150458_ak, false).func_77655_b("witchery:seedswolfsbane").func_111206_d("witchery:ingredient.seedswolfsbane");
        this.SEEDS_GARLIC = new ItemWitchSeeds(Witchery.Blocks.CROP_GARLIC, null, Blocks.field_150458_ak, false).func_77655_b("witchery:garlic").func_111206_d("witchery:garlic");
        this.BUCKET_FLOWINGSPIRIT = WitcheryFluids.bind((ItemBucketSpirit)new ItemBucketSpirit().func_77655_b("witchery:bucketspirit").func_111206_d("witchery:bucket_spirit").func_77642_a(Items.field_151133_ar), Witchery.Fluids.FLOWING_SPIRIT, Witchery.Blocks.FLOWING_SPIRIT);
        this.BUCKET_HOLLOWTEARS = WitcheryFluids.bind((ItemBucketSpirit)new ItemBucketSpirit().func_77655_b("witchery:buckethollowtears").func_111206_d("witchery:bucket_hollowtears").func_77642_a(Items.field_151133_ar), Witchery.Fluids.HOLLOW_TEARS, Witchery.Blocks.HOLLOW_TEARS);
        this.BUCKET_BREW = WitcheryFluids.bind(new ItemBrewBucket().func_77655_b("witchery:bucketbrew").func_111206_d("witchery:bucket_brew").func_77642_a(Items.field_151133_ar), Witchery.Fluids.BREW, 1000);
    }
}

