/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.common.registry.GameRegistry
 *  net.minecraft.block.Block
 *  net.minecraft.block.material.Material
 *  net.minecraft.init.Blocks
 *  net.minecraft.item.EnumRarity
 *  net.minecraftforge.fluids.Fluid
 *  net.minecraftforge.fluids.FluidRegistry
 */
package thaumcraft.common.config;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.item.EnumRarity;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.common.blocks.BlockAiry;
import thaumcraft.common.blocks.BlockAiryItem;
import thaumcraft.common.blocks.BlockAlchemyFurnace;
import thaumcraft.common.blocks.BlockArcaneDoor;
import thaumcraft.common.blocks.BlockArcaneFurnace;
import thaumcraft.common.blocks.BlockCandle;
import thaumcraft.common.blocks.BlockCandleItem;
import thaumcraft.common.blocks.BlockChestHungry;
import thaumcraft.common.blocks.BlockCosmeticOpaque;
import thaumcraft.common.blocks.BlockCosmeticOpaqueItem;
import thaumcraft.common.blocks.BlockCosmeticSolid;
import thaumcraft.common.blocks.BlockCosmeticSolidItem;
import thaumcraft.common.blocks.BlockCosmeticStairs;
import thaumcraft.common.blocks.BlockCosmeticStoneSlab;
import thaumcraft.common.blocks.BlockCosmeticStoneSlabItem;
import thaumcraft.common.blocks.BlockCosmeticWoodSlab;
import thaumcraft.common.blocks.BlockCosmeticWoodSlabItem;
import thaumcraft.common.blocks.BlockCrystal;
import thaumcraft.common.blocks.BlockCrystalItem;
import thaumcraft.common.blocks.BlockCustomOre;
import thaumcraft.common.blocks.BlockCustomOreItem;
import thaumcraft.common.blocks.BlockCustomPlant;
import thaumcraft.common.blocks.BlockCustomPlantItem;
import thaumcraft.common.blocks.BlockEldritch;
import thaumcraft.common.blocks.BlockEldritchItem;
import thaumcraft.common.blocks.BlockEldritchNothing;
import thaumcraft.common.blocks.BlockEldritchPortal;
import thaumcraft.common.blocks.BlockEssentiaReservoir;
import thaumcraft.common.blocks.BlockEssentiaReservoirItem;
import thaumcraft.common.blocks.BlockFluidDeath;
import thaumcraft.common.blocks.BlockFluidPure;
import thaumcraft.common.blocks.BlockFluxGas;
import thaumcraft.common.blocks.BlockFluxGasItem;
import thaumcraft.common.blocks.BlockFluxGoo;
import thaumcraft.common.blocks.BlockFluxGooItem;
import thaumcraft.common.blocks.BlockHole;
import thaumcraft.common.blocks.BlockJar;
import thaumcraft.common.blocks.BlockJarItem;
import thaumcraft.common.blocks.BlockLifter;
import thaumcraft.common.blocks.BlockLoot;
import thaumcraft.common.blocks.BlockLootItem;
import thaumcraft.common.blocks.BlockMagicBox;
import thaumcraft.common.blocks.BlockMagicalLeaves;
import thaumcraft.common.blocks.BlockMagicalLeavesItem;
import thaumcraft.common.blocks.BlockMagicalLog;
import thaumcraft.common.blocks.BlockMagicalLogItem;
import thaumcraft.common.blocks.BlockManaPod;
import thaumcraft.common.blocks.BlockMetalDevice;
import thaumcraft.common.blocks.BlockMetalDeviceItem;
import thaumcraft.common.blocks.BlockMirror;
import thaumcraft.common.blocks.BlockMirrorItem;
import thaumcraft.common.blocks.BlockStoneDevice;
import thaumcraft.common.blocks.BlockStoneDeviceItem;
import thaumcraft.common.blocks.BlockTable;
import thaumcraft.common.blocks.BlockTableItem;
import thaumcraft.common.blocks.BlockTaint;
import thaumcraft.common.blocks.BlockTaintFibres;
import thaumcraft.common.blocks.BlockTaintFibresItem;
import thaumcraft.common.blocks.BlockTaintItem;
import thaumcraft.common.blocks.BlockTube;
import thaumcraft.common.blocks.BlockTubeItem;
import thaumcraft.common.blocks.BlockWarded;
import thaumcraft.common.blocks.BlockWoodenDevice;
import thaumcraft.common.blocks.BlockWoodenDeviceItem;
import thaumcraft.common.blocks.CustomStepSound;
import thaumcraft.common.tiles.TileAlchemyFurnace;
import thaumcraft.common.tiles.TileAlchemyFurnaceAdvanced;
import thaumcraft.common.tiles.TileAlchemyFurnaceAdvancedNozzle;
import thaumcraft.common.tiles.TileAlembic;
import thaumcraft.common.tiles.TileArcaneBore;
import thaumcraft.common.tiles.TileArcaneBoreBase;
import thaumcraft.common.tiles.TileArcaneFurnace;
import thaumcraft.common.tiles.TileArcaneFurnaceNozzle;
import thaumcraft.common.tiles.TileArcaneLamp;
import thaumcraft.common.tiles.TileArcaneLampFertility;
import thaumcraft.common.tiles.TileArcaneLampGrowth;
import thaumcraft.common.tiles.TileArcanePressurePlate;
import thaumcraft.common.tiles.TileArcaneWorkbench;
import thaumcraft.common.tiles.TileBanner;
import thaumcraft.common.tiles.TileBellows;
import thaumcraft.common.tiles.TileBrainbox;
import thaumcraft.common.tiles.TileCentrifuge;
import thaumcraft.common.tiles.TileChestHungry;
import thaumcraft.common.tiles.TileCrucible;
import thaumcraft.common.tiles.TileCrystal;
import thaumcraft.common.tiles.TileDeconstructionTable;
import thaumcraft.common.tiles.TileEldritchAltar;
import thaumcraft.common.tiles.TileEldritchCap;
import thaumcraft.common.tiles.TileEldritchCrabSpawner;
import thaumcraft.common.tiles.TileEldritchCrystal;
import thaumcraft.common.tiles.TileEldritchLock;
import thaumcraft.common.tiles.TileEldritchNothing;
import thaumcraft.common.tiles.TileEldritchObelisk;
import thaumcraft.common.tiles.TileEldritchPortal;
import thaumcraft.common.tiles.TileEldritchTrap;
import thaumcraft.common.tiles.TileEssentiaCrystalizer;
import thaumcraft.common.tiles.TileEssentiaReservoir;
import thaumcraft.common.tiles.TileEtherealBloom;
import thaumcraft.common.tiles.TileFluxScrubber;
import thaumcraft.common.tiles.TileFocalManipulator;
import thaumcraft.common.tiles.TileGrate;
import thaumcraft.common.tiles.TileHole;
import thaumcraft.common.tiles.TileInfusionMatrix;
import thaumcraft.common.tiles.TileInfusionPillar;
import thaumcraft.common.tiles.TileJarBrain;
import thaumcraft.common.tiles.TileJarFillable;
import thaumcraft.common.tiles.TileJarFillableVoid;
import thaumcraft.common.tiles.TileJarNode;
import thaumcraft.common.tiles.TileLifter;
import thaumcraft.common.tiles.TileMagicBox;
import thaumcraft.common.tiles.TileMagicWorkbenchCharger;
import thaumcraft.common.tiles.TileManaPod;
import thaumcraft.common.tiles.TileMirror;
import thaumcraft.common.tiles.TileMirrorEssentia;
import thaumcraft.common.tiles.TileNitor;
import thaumcraft.common.tiles.TileNode;
import thaumcraft.common.tiles.TileNodeConverter;
import thaumcraft.common.tiles.TileNodeEnergized;
import thaumcraft.common.tiles.TileNodeStabilizer;
import thaumcraft.common.tiles.TileOwned;
import thaumcraft.common.tiles.TilePedestal;
import thaumcraft.common.tiles.TileResearchTable;
import thaumcraft.common.tiles.TileSensor;
import thaumcraft.common.tiles.TileSpa;
import thaumcraft.common.tiles.TileTable;
import thaumcraft.common.tiles.TileThaumatorium;
import thaumcraft.common.tiles.TileThaumatoriumTop;
import thaumcraft.common.tiles.TileTube;
import thaumcraft.common.tiles.TileTubeBuffer;
import thaumcraft.common.tiles.TileTubeFilter;
import thaumcraft.common.tiles.TileTubeOneway;
import thaumcraft.common.tiles.TileTubeRestrict;
import thaumcraft.common.tiles.TileTubeValve;
import thaumcraft.common.tiles.TileVisRelay;
import thaumcraft.common.tiles.TileWandPedestal;
import thaumcraft.common.tiles.TileWarded;
import thaumcraft.common.tiles.TileWardingStone;
import thaumcraft.common.tiles.TileWardingStoneFence;

public class ConfigBlocks {
    public static Fluid FLUXGOO = new Fluid("fluxGoo").setGaseous(false).setLuminosity(7).setDensity(8).setViscosity(6000);
    public static Fluid FLUXGAS = new Fluid("fluxGas").setGaseous(true).setLuminosity(7).setDensity(-4).setViscosity(2500);
    public static Fluid FLUIDPURE = new Fluid("fluidPure").setGaseous(false).setLuminosity(10).setViscosity(1000).setRarity(EnumRarity.rare);
    public static Fluid FLUIDDEATH = new Fluid("fluidDeath").setGaseous(false).setLuminosity(8).setViscosity(1500).setRarity(EnumRarity.rare);
    public static Block blockFluxGoo;
    public static Block blockFluxGas;
    public static Block blockFluidPure;
    public static Block blockFluidDeath;
    public static Block blockHole;
    public static Block blockArcaneFurnace;
    public static Block blockMetalDevice;
    public static Block blockMagicalLog;
    public static Block blockStoneDevice;
    public static Block blockWoodenDevice;
    public static Block blockMagicalLeaves;
    public static Block blockTable;
    public static Block blockChestHungry;
    public static Block blockCustomOre;
    public static Block blockCustomPlant;
    public static Block blockCandle;
    public static Block blockJar;
    public static Block blockArcaneDoor;
    public static Block blockWarded;
    public static Block blockLifter;
    public static Block blockAiry;
    public static Block blockCrystal;
    public static Block blockCosmeticOpaque;
    public static Block blockCosmeticSolid;
    public static Block blockMirror;
    public static Block blockTaint;
    public static Block blockTaintFibres;
    public static Block blockManaPod;
    public static Block blockTube;
    public static Block blockMagicBox;
    public static Block blockEldritch;
    public static Block blockEldritchPortal;
    public static Block blockEssentiaReservoir;
    public static Block blockStairsArcaneStone;
    public static Block blockStairsSilverwood;
    public static Block blockStairsGreatwood;
    public static Block blockStairsEldritch;
    public static Block blockSlabWood;
    public static Block blockSlabStone;
    public static Block blockDoubleSlabWood;
    public static Block blockDoubleSlabStone;
    public static Block blockEldritchNothing;
    public static Block blockAlchemyFurnace;
    public static Block blockLootUrn;
    public static Block blockLootCrate;
    public static int blockCosmeticOpaqueRI;
    public static int blockWoodenDeviceRI;
    public static int blockLifterRI;
    public static int blockCrystalRI;
    public static int blockFluxGasRI;
    public static int blockCustomOreRI;
    public static int blockTaintRI;
    public static int blockTaintFibreRI;
    public static int blockMirrorRI;
    public static int blockCandleRI;
    public static int blockWardedRI;
    public static int blockArcaneFurnaceRI;
    public static int blockMetalDeviceRI;
    public static int blockStoneDeviceRI;
    public static int blockChestHungryRI;
    public static int blockTableRI;
    public static int blockJarRI;
    public static int blockLootUrnRI;
    public static int blockLootCrateRI;
    public static int blockTubeRI;
    public static int blockEssentiaReservoirRI;
    public static int blockEldritchRI;

    public static void init() {
        ConfigBlocks.initializeBlocks();
        ConfigBlocks.registerBlocks();
        ConfigBlocks.registerTileEntities();
        blockCustomOre.setHarvestLevel("pickaxe", 2, 0);
        blockCustomOre.setHarvestLevel("pickaxe", 2, 7);
        ThaumcraftApi.portableHoleBlackList.add(Blocks.field_150324_C);
        ThaumcraftApi.portableHoleBlackList.add(blockEldritch);
        ThaumcraftApi.portableHoleBlackList.add(blockEldritchPortal);
        ThaumcraftApi.portableHoleBlackList.add((Block)Blocks.field_150331_J);
        ThaumcraftApi.portableHoleBlackList.add((Block)Blocks.field_150332_K);
        ThaumcraftApi.portableHoleBlackList.add((Block)Blocks.field_150320_F);
        ThaumcraftApi.portableHoleBlackList.add((Block)Blocks.field_150326_M);
        ThaumcraftApi.portableHoleBlackList.add(Blocks.field_150466_ao);
        ThaumcraftApi.portableHoleBlackList.add(Blocks.field_150454_av);
        ThaumcraftApi.portableHoleBlackList.add(blockFluxGoo);
        ThaumcraftApi.portableHoleBlackList.add(blockFluxGas);
        ThaumcraftApi.portableHoleBlackList.add(blockArcaneFurnace);
    }

    private static void initializeBlocks() {
        FluidRegistry.registerFluid((Fluid)FLUXGOO);
        FluidRegistry.registerFluid((Fluid)FLUIDPURE);
        FluidRegistry.registerFluid((Fluid)FLUIDDEATH);
        blockFluxGoo = new BlockFluxGoo().func_149663_c("blockFluxGoo");
        blockFluxGas = new BlockFluxGas().func_149663_c("blockFluxGas");
        blockHole = new BlockHole().func_149663_c("blockHole");
        blockCustomOre = new BlockCustomOre().func_149663_c("blockCustomOre");
        blockCustomPlant = new BlockCustomPlant().func_149663_c("blockCustomPlant");
        blockMagicalLog = new BlockMagicalLog().func_149663_c("blockMagicalLog");
        blockMagicalLeaves = new BlockMagicalLeaves().func_149663_c("blockMagicalLeaves");
        blockArcaneFurnace = new BlockArcaneFurnace().func_149663_c("blockArcaneFurnace");
        blockMetalDevice = new BlockMetalDevice().func_149663_c("blockMetalDevice");
        blockAlchemyFurnace = new BlockAlchemyFurnace().func_149663_c("blockAlchemyFurnace");
        blockTable = new BlockTable().func_149663_c("blockTable");
        blockChestHungry = new BlockChestHungry().func_149663_c("blockChestHungry");
        blockCandle = new BlockCandle().func_149663_c("blockCandle");
        blockJar = new BlockJar().func_149663_c("blockJar");
        blockArcaneDoor = new BlockArcaneDoor().func_149663_c("blockArcaneDoor");
        blockWoodenDevice = new BlockWoodenDevice().func_149663_c("blockWoodenDevice");
        blockLifter = new BlockLifter().func_149663_c("blockLifter");
        blockAiry = new BlockAiry().func_149663_c("blockAiry");
        blockCrystal = new BlockCrystal().func_149663_c("blockCrystal");
        blockCosmeticOpaque = new BlockCosmeticOpaque().func_149663_c("blockCosmeticOpaque");
        blockCosmeticSolid = new BlockCosmeticSolid().func_149663_c("blockCosmeticSolid");
        blockMirror = new BlockMirror().func_149663_c("blockMirror");
        blockTaint = new BlockTaint().func_149663_c("blockTaint");
        blockTaintFibres = new BlockTaintFibres().func_149663_c("blockTaintFibres");
        blockStoneDevice = new BlockStoneDevice().func_149663_c("blockStoneDevice");
        blockManaPod = new BlockManaPod().func_149663_c("blockManaPod");
        blockTube = new BlockTube().func_149663_c("blockTube");
        blockWarded = new BlockWarded().func_149663_c("blockWarded");
        blockMagicBox = new BlockMagicBox().func_149663_c("blockMagicBox");
        blockFluidPure = new BlockFluidPure().func_149663_c("blockFluidPure");
        blockFluidDeath = new BlockFluidDeath().func_149663_c("blockFluidDeath");
        blockEldritch = new BlockEldritch().func_149663_c("blockEldritch");
        blockEldritchPortal = new BlockEldritchPortal().func_149663_c("blockPortalEldritch");
        blockEssentiaReservoir = new BlockEssentiaReservoir().func_149663_c("blockEssentiaReservoir");
        blockEldritchNothing = new BlockEldritchNothing().func_149663_c("blockPortalNothing");
        blockStairsArcaneStone = new BlockCosmeticStairs(blockCosmeticSolid, 7).func_149663_c("blockStairsArcaneStone");
        blockStairsGreatwood = new BlockCosmeticStairs(blockWoodenDevice, 6).func_149663_c("blockStairsGreatwood");
        blockStairsSilverwood = new BlockCosmeticStairs(blockWoodenDevice, 7).func_149663_c("blockStairsSilverwood");
        blockStairsEldritch = new BlockCosmeticStairs(blockCosmeticSolid, 11).func_149663_c("blockStairsEldritch");
        blockSlabWood = new BlockCosmeticWoodSlab(false).func_149711_c(2.0f).func_149752_b(5.0f).func_149672_a(Block.field_149766_f).func_149663_c("blockCosmeticSlabWood");
        blockSlabStone = new BlockCosmeticStoneSlab(false).func_149711_c(2.0f).func_149752_b(10.0f).func_149672_a(Block.field_149780_i).func_149663_c("blockCosmeticSlabStone");
        blockDoubleSlabWood = new BlockCosmeticWoodSlab(true).func_149711_c(2.0f).func_149752_b(5.0f).func_149672_a(Block.field_149766_f).func_149663_c("blockCosmeticDoubleSlabWood");
        blockDoubleSlabStone = new BlockCosmeticStoneSlab(true).func_149711_c(2.0f).func_149752_b(10.0f).func_149672_a(Block.field_149780_i).func_149663_c("blockCosmeticDoubleSlabStone");
        blockLootUrn = new BlockLoot(Material.field_151571_B, "urn", 1).func_149672_a(new CustomStepSound("urnbreak", 1.0f, 0.7f)).func_149663_c("blockLootUrn");
        blockLootCrate = new BlockLoot(Material.field_151575_d, "crate", 2).func_149672_a(Block.field_149766_f).func_149663_c("blockLootCrate");
    }

    private static void registerBlocks() {
        GameRegistry.registerBlock((Block)blockFluxGoo, BlockFluxGooItem.class, (String)"blockFluxGoo");
        GameRegistry.registerBlock((Block)blockFluxGas, BlockFluxGasItem.class, (String)"blockFluxGas");
        GameRegistry.registerBlock((Block)blockFluidPure, (String)"blockFluidPure");
        GameRegistry.registerBlock((Block)blockFluidDeath, (String)"blockFluidDeath");
        GameRegistry.registerBlock((Block)blockCustomOre, BlockCustomOreItem.class, (String)"blockCustomOre");
        GameRegistry.registerBlock((Block)blockMagicalLog, BlockMagicalLogItem.class, (String)"blockMagicalLog");
        GameRegistry.registerBlock((Block)blockMagicalLeaves, BlockMagicalLeavesItem.class, (String)"blockMagicalLeaves");
        GameRegistry.registerBlock((Block)blockCustomPlant, BlockCustomPlantItem.class, (String)"blockCustomPlant");
        GameRegistry.registerBlock((Block)blockTaint, BlockTaintItem.class, (String)"blockTaint");
        GameRegistry.registerBlock((Block)blockTaintFibres, BlockTaintFibresItem.class, (String)"blockTaintFibres");
        GameRegistry.registerBlock((Block)blockCosmeticOpaque, BlockCosmeticOpaqueItem.class, (String)"blockCosmeticOpaque");
        GameRegistry.registerBlock((Block)blockCosmeticSolid, BlockCosmeticSolidItem.class, (String)"blockCosmeticSolid");
        GameRegistry.registerBlock((Block)blockCrystal, BlockCrystalItem.class, (String)"blockCrystal");
        GameRegistry.registerBlock((Block)blockTube, BlockTubeItem.class, (String)"blockTube");
        GameRegistry.registerBlock((Block)blockMetalDevice, BlockMetalDeviceItem.class, (String)"blockMetalDevice");
        GameRegistry.registerBlock((Block)blockWoodenDevice, BlockWoodenDeviceItem.class, (String)"blockWoodenDevice");
        GameRegistry.registerBlock((Block)blockStoneDevice, BlockStoneDeviceItem.class, (String)"blockStoneDevice");
        GameRegistry.registerBlock((Block)blockMirror, BlockMirrorItem.class, (String)"blockMirror");
        GameRegistry.registerBlock((Block)blockTable, BlockTableItem.class, (String)"blockTable");
        GameRegistry.registerBlock((Block)blockChestHungry, (String)"blockChestHungry");
        GameRegistry.registerBlock((Block)blockArcaneDoor, (String)"blockArcaneDoor");
        GameRegistry.registerBlock((Block)blockLifter, (String)"blockLifter");
        GameRegistry.registerBlock((Block)blockMagicBox, (String)"blockMagicBox");
        GameRegistry.registerBlock((Block)blockAlchemyFurnace, (String)"blockAlchemyFurnace");
        GameRegistry.registerBlock((Block)blockJar, BlockJarItem.class, (String)"blockJar");
        GameRegistry.registerBlock((Block)blockCandle, BlockCandleItem.class, (String)"blockCandle");
        GameRegistry.registerBlock((Block)blockEldritch, BlockEldritchItem.class, (String)"blockEldritch");
        GameRegistry.registerBlock((Block)blockAiry, BlockAiryItem.class, (String)"blockAiry");
        GameRegistry.registerBlock((Block)blockManaPod, (String)"blockManaPod");
        GameRegistry.registerBlock((Block)blockArcaneFurnace, (String)"blockArcaneFurnace");
        GameRegistry.registerBlock((Block)blockWarded, (String)"blockWarded");
        GameRegistry.registerBlock((Block)blockHole, (String)"blockHole");
        GameRegistry.registerBlock((Block)blockEldritchPortal, (String)"blockPortalEldritch");
        GameRegistry.registerBlock((Block)blockEssentiaReservoir, BlockEssentiaReservoirItem.class, (String)"blockEssentiaReservoir");
        GameRegistry.registerBlock((Block)blockEldritchNothing, (String)"blockEldritchNothing");
        GameRegistry.registerBlock((Block)blockStairsArcaneStone, (String)"blockStairsArcaneStone");
        GameRegistry.registerBlock((Block)blockStairsGreatwood, (String)"blockStairsGreatwood");
        GameRegistry.registerBlock((Block)blockStairsSilverwood, (String)"blockStairsSilverwood");
        GameRegistry.registerBlock((Block)blockStairsEldritch, (String)"blockStairsEldritch");
        GameRegistry.registerBlock((Block)blockSlabWood, BlockCosmeticWoodSlabItem.class, (String)"blockCosmeticSlabWood");
        GameRegistry.registerBlock((Block)blockSlabStone, BlockCosmeticStoneSlabItem.class, (String)"blockCosmeticSlabStone");
        GameRegistry.registerBlock((Block)blockDoubleSlabWood, (String)"blockCosmeticDoubleSlabWood");
        GameRegistry.registerBlock((Block)blockDoubleSlabStone, (String)"blockCosmeticDoubleSlabStone");
        GameRegistry.registerBlock((Block)blockLootUrn, BlockLootItem.class, (String)"blockLootUrn");
        GameRegistry.registerBlock((Block)blockLootCrate, BlockLootItem.class, (String)"blockLootCrate");
    }

    private static void registerTileEntities() {
        GameRegistry.registerTileEntity(TileHole.class, (String)"TileHole");
        GameRegistry.registerTileEntity(TileArcaneFurnace.class, (String)"TileArcaneFurnace");
        GameRegistry.registerTileEntity(TileArcaneFurnaceNozzle.class, (String)"TileArcaneFurnaceNozzle");
        GameRegistry.registerTileEntity(TileCrucible.class, (String)"TileCrucible");
        GameRegistry.registerTileEntity(TileAlembic.class, (String)"TileSiphon");
        GameRegistry.registerTileEntity(TileJarFillable.class, (String)"TileJar");
        GameRegistry.registerTileEntity(TileJarFillableVoid.class, (String)"TileJarVoid");
        GameRegistry.registerTileEntity(TileJarNode.class, (String)"TileJarNode");
        GameRegistry.registerTileEntity(TileJarBrain.class, (String)"TileJarBrain");
        GameRegistry.registerTileEntity(TileResearchTable.class, (String)"TileResearchTable");
        GameRegistry.registerTileEntity(TileTable.class, (String)"TileTable");
        GameRegistry.registerTileEntity(TileArcaneWorkbench.class, (String)"TileArcaneWorkbench");
        GameRegistry.registerTileEntity(TileChestHungry.class, (String)"TileChestHungry");
        GameRegistry.registerTileEntity(TileBellows.class, (String)"TileBellows");
        GameRegistry.registerTileEntity(TileSensor.class, (String)"TileSensor");
        GameRegistry.registerTileEntity(TileArcanePressurePlate.class, (String)"TileArcanePressurePlate");
        GameRegistry.registerTileEntity(TileArcaneBore.class, (String)"TileArcaneBore");
        GameRegistry.registerTileEntity(TileArcaneBoreBase.class, (String)"TileArcaneBoreBase");
        GameRegistry.registerTileEntity(TileArcaneLamp.class, (String)"TileArcaneLamp");
        GameRegistry.registerTileEntity(TileArcaneLampGrowth.class, (String)"TileArcaneLampGrowth");
        GameRegistry.registerTileEntity(TileArcaneLampFertility.class, (String)"TileArcaneLampFertility");
        GameRegistry.registerTileEntity(TileOwned.class, (String)"TileOwned");
        GameRegistry.registerTileEntity(TileLifter.class, (String)"TileLifter");
        GameRegistry.registerTileEntity(TileNitor.class, (String)"TileNitor");
        GameRegistry.registerTileEntity(TileNode.class, (String)"TileNode");
        GameRegistry.registerTileEntity(TileCrystal.class, (String)"TileCrystal");
        GameRegistry.registerTileEntity(TileEldritchCrystal.class, (String)"TileEldritchCrystal");
        GameRegistry.registerTileEntity(TileMirror.class, (String)"TileMirror");
        GameRegistry.registerTileEntity(TileMirrorEssentia.class, (String)"TileMirrorEssentia");
        GameRegistry.registerTileEntity(TilePedestal.class, (String)"TilePedestal");
        GameRegistry.registerTileEntity(TileWandPedestal.class, (String)"TileWandPedestal");
        GameRegistry.registerTileEntity(TileInfusionMatrix.class, (String)"TileInfusionStone");
        GameRegistry.registerTileEntity(TileInfusionPillar.class, (String)"TileInfusionPillar");
        GameRegistry.registerTileEntity(TileAlchemyFurnace.class, (String)"TileAlchemyFurnace");
        GameRegistry.registerTileEntity(TileAlchemyFurnaceAdvanced.class, (String)"TileAlchemyFurnaceAdvanced");
        GameRegistry.registerTileEntity(TileAlchemyFurnaceAdvancedNozzle.class, (String)"TileAlchemyFurnaceAdvancedNozzle");
        GameRegistry.registerTileEntity(TileDeconstructionTable.class, (String)"TileDeconstructionTable");
        GameRegistry.registerTileEntity(TileEtherealBloom.class, (String)"TilePurifyTotem");
        GameRegistry.registerTileEntity(TileTube.class, (String)"TileTube");
        GameRegistry.registerTileEntity(TileTubeValve.class, (String)"TileTubeValve");
        GameRegistry.registerTileEntity(TileCentrifuge.class, (String)"TileCentrifuge");
        GameRegistry.registerTileEntity(TileTubeFilter.class, (String)"TileTubeFilter");
        GameRegistry.registerTileEntity(TileTubeBuffer.class, (String)"TileTubeBuffer");
        GameRegistry.registerTileEntity(TileTubeRestrict.class, (String)"TileTubeRestrict");
        GameRegistry.registerTileEntity(TileTubeOneway.class, (String)"TileTubeOneway");
        GameRegistry.registerTileEntity(TileThaumatorium.class, (String)"TileThaumatorium");
        GameRegistry.registerTileEntity(TileThaumatoriumTop.class, (String)"TileThaumatoriumTop");
        GameRegistry.registerTileEntity(TileBrainbox.class, (String)"TileBrainbox");
        GameRegistry.registerTileEntity(TileWarded.class, (String)"TileWarded");
        GameRegistry.registerTileEntity(TileGrate.class, (String)"TileGrate");
        GameRegistry.registerTileEntity(TileWardingStone.class, (String)"TileWardingStone");
        GameRegistry.registerTileEntity(TileWardingStoneFence.class, (String)"TileWardingStoneFence");
        GameRegistry.registerTileEntity(TileMagicBox.class, (String)"TileMagicBox");
        GameRegistry.registerTileEntity(TileNodeStabilizer.class, (String)"TileNodeStabilizer");
        GameRegistry.registerTileEntity(TileVisRelay.class, (String)"TileVisRelay");
        GameRegistry.registerTileEntity(TileNodeEnergized.class, (String)"TileNodeEnergized");
        GameRegistry.registerTileEntity(TileNodeConverter.class, (String)"TileNodeConverter");
        GameRegistry.registerTileEntity(TileMagicWorkbenchCharger.class, (String)"TileMagicWorkbenchCharger");
        GameRegistry.registerTileEntity(TileManaPod.class, (String)"TileManaPod");
        GameRegistry.registerTileEntity(TileSpa.class, (String)"TileSpa");
        GameRegistry.registerTileEntity(TileEldritchAltar.class, (String)"TileEldritchAltar");
        GameRegistry.registerTileEntity(TileEldritchObelisk.class, (String)"TileEldritchObelisk");
        GameRegistry.registerTileEntity(TileEldritchCap.class, (String)"TileEldritchCap");
        GameRegistry.registerTileEntity(TileBanner.class, (String)"TileBanner");
        GameRegistry.registerTileEntity(TileEldritchPortal.class, (String)"TileEldritchPortal");
        GameRegistry.registerTileEntity(TileEssentiaReservoir.class, (String)"TileEssentiaReservoir");
        GameRegistry.registerTileEntity(TileEssentiaCrystalizer.class, (String)"TileEssentiaCrystalizer");
        GameRegistry.registerTileEntity(TileEldritchNothing.class, (String)"TileEldritchNothing");
        GameRegistry.registerTileEntity(TileEldritchLock.class, (String)"TileEldritchLock");
        GameRegistry.registerTileEntity(TileEldritchCrabSpawner.class, (String)"TileEldritchCrabSpawner");
        GameRegistry.registerTileEntity(TileFocalManipulator.class, (String)"TileFocalManipulator");
        GameRegistry.registerTileEntity(TileFluxScrubber.class, (String)"TileFluxScrubber");
        GameRegistry.registerTileEntity(TileEldritchTrap.class, (String)"TileEldritchTrap");
    }

    static {
        blockCosmeticOpaqueRI = -1;
        blockWoodenDeviceRI = -1;
        blockLifterRI = -1;
        blockCrystalRI = -1;
        blockFluxGasRI = -1;
        blockCustomOreRI = -1;
        blockTaintRI = -1;
        blockTaintFibreRI = -1;
        blockMirrorRI = -1;
        blockCandleRI = -1;
        blockWardedRI = -1;
        blockArcaneFurnaceRI = -1;
        blockMetalDeviceRI = -1;
        blockStoneDeviceRI = -1;
        blockChestHungryRI = -1;
        blockTableRI = -1;
        blockJarRI = -1;
        blockLootUrnRI = -1;
        blockLootCrateRI = -1;
        blockTubeRI = -1;
        blockEssentiaReservoirRI = -1;
        blockEldritchRI = -1;
    }
}

