/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.common.registry.GameRegistry
 *  net.minecraft.init.Items
 *  net.minecraft.item.Item
 *  net.minecraft.item.ItemArmor$ArmorMaterial
 *  net.minecraft.item.ItemStack
 *  net.minecraftforge.fluids.FluidContainerRegistry
 *  net.minecraftforge.fluids.FluidStack
 *  net.minecraftforge.oredict.OreDictionary
 */
package thaumcraft.common.config;

import cpw.mods.fml.common.registry.GameRegistry;
import java.util.Arrays;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.FluidContainerRegistry;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.oredict.OreDictionary;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.wands.StaffRod;
import thaumcraft.api.wands.WandCap;
import thaumcraft.api.wands.WandRod;
import thaumcraft.common.blocks.ItemArcaneDoor;
import thaumcraft.common.blocks.ItemJarFilled;
import thaumcraft.common.blocks.ItemJarNode;
import thaumcraft.common.config.Config;
import thaumcraft.common.config.ConfigBlocks;
import thaumcraft.common.entities.ItemSpawnerEgg;
import thaumcraft.common.entities.golems.ItemGolemBell;
import thaumcraft.common.entities.golems.ItemGolemCore;
import thaumcraft.common.entities.golems.ItemGolemDecoration;
import thaumcraft.common.entities.golems.ItemGolemPlacer;
import thaumcraft.common.entities.golems.ItemGolemUpgrade;
import thaumcraft.common.entities.golems.ItemTrunkSpawner;
import thaumcraft.common.items.ItemBathSalts;
import thaumcraft.common.items.ItemBottleTaint;
import thaumcraft.common.items.ItemBucketDeath;
import thaumcraft.common.items.ItemBucketPure;
import thaumcraft.common.items.ItemCompassStone;
import thaumcraft.common.items.ItemCrystalEssence;
import thaumcraft.common.items.ItemEldritchObject;
import thaumcraft.common.items.ItemEssence;
import thaumcraft.common.items.ItemInkwell;
import thaumcraft.common.items.ItemKey;
import thaumcraft.common.items.ItemLootBag;
import thaumcraft.common.items.ItemManaBean;
import thaumcraft.common.items.ItemNugget;
import thaumcraft.common.items.ItemNuggetEdible;
import thaumcraft.common.items.ItemResearchNotes;
import thaumcraft.common.items.ItemResource;
import thaumcraft.common.items.ItemSanitySoap;
import thaumcraft.common.items.ItemShard;
import thaumcraft.common.items.ItemTripleMeatTreat;
import thaumcraft.common.items.ItemWispEssence;
import thaumcraft.common.items.ItemZombieBrain;
import thaumcraft.common.items.armor.ItemBootsTraveller;
import thaumcraft.common.items.armor.ItemCultistBoots;
import thaumcraft.common.items.armor.ItemCultistLeaderArmor;
import thaumcraft.common.items.armor.ItemCultistPlateArmor;
import thaumcraft.common.items.armor.ItemCultistRobeArmor;
import thaumcraft.common.items.armor.ItemFortressArmor;
import thaumcraft.common.items.armor.ItemGoggles;
import thaumcraft.common.items.armor.ItemHoverHarness;
import thaumcraft.common.items.armor.ItemRobeArmor;
import thaumcraft.common.items.armor.ItemThaumiumArmor;
import thaumcraft.common.items.armor.ItemVoidArmor;
import thaumcraft.common.items.armor.ItemVoidRobeArmor;
import thaumcraft.common.items.baubles.ItemAmuletRunic;
import thaumcraft.common.items.baubles.ItemAmuletVis;
import thaumcraft.common.items.baubles.ItemBaubleBlanks;
import thaumcraft.common.items.baubles.ItemGirdleHover;
import thaumcraft.common.items.baubles.ItemGirdleRunic;
import thaumcraft.common.items.baubles.ItemRingRunic;
import thaumcraft.common.items.equipment.ItemBowBone;
import thaumcraft.common.items.equipment.ItemCrimsonSword;
import thaumcraft.common.items.equipment.ItemElementalAxe;
import thaumcraft.common.items.equipment.ItemElementalHoe;
import thaumcraft.common.items.equipment.ItemElementalPickaxe;
import thaumcraft.common.items.equipment.ItemElementalShovel;
import thaumcraft.common.items.equipment.ItemElementalSword;
import thaumcraft.common.items.equipment.ItemPrimalArrow;
import thaumcraft.common.items.equipment.ItemPrimalCrusher;
import thaumcraft.common.items.equipment.ItemThaumiumAxe;
import thaumcraft.common.items.equipment.ItemThaumiumHoe;
import thaumcraft.common.items.equipment.ItemThaumiumPickaxe;
import thaumcraft.common.items.equipment.ItemThaumiumShovel;
import thaumcraft.common.items.equipment.ItemThaumiumSword;
import thaumcraft.common.items.equipment.ItemVoidAxe;
import thaumcraft.common.items.equipment.ItemVoidHoe;
import thaumcraft.common.items.equipment.ItemVoidPickaxe;
import thaumcraft.common.items.equipment.ItemVoidShovel;
import thaumcraft.common.items.equipment.ItemVoidSword;
import thaumcraft.common.items.relics.ItemHandMirror;
import thaumcraft.common.items.relics.ItemResonator;
import thaumcraft.common.items.relics.ItemSanityChecker;
import thaumcraft.common.items.relics.ItemThaumometer;
import thaumcraft.common.items.relics.ItemThaumonomicon;
import thaumcraft.common.items.wands.ItemFocusPouchBauble;
import thaumcraft.common.items.wands.ItemWandCap;
import thaumcraft.common.items.wands.ItemWandCasting;
import thaumcraft.common.items.wands.ItemWandRod;
import thaumcraft.common.items.wands.WandRodPrimalOnUpdate;
import thaumcraft.common.items.wands.foci.ItemFocusExcavation;
import thaumcraft.common.items.wands.foci.ItemFocusFire;
import thaumcraft.common.items.wands.foci.ItemFocusFrost;
import thaumcraft.common.items.wands.foci.ItemFocusHellbat;
import thaumcraft.common.items.wands.foci.ItemFocusPech;
import thaumcraft.common.items.wands.foci.ItemFocusPortableHole;
import thaumcraft.common.items.wands.foci.ItemFocusPrimal;
import thaumcraft.common.items.wands.foci.ItemFocusShock;
import thaumcraft.common.items.wands.foci.ItemFocusTrade;
import thaumcraft.common.items.wands.foci.ItemFocusWarding;

public class ConfigItems {
    public static WandCap WAND_CAP_IRON;
    public static WandCap WAND_CAP_COPPER;
    public static WandCap WAND_CAP_GOLD;
    public static WandCap WAND_CAP_SILVER;
    public static WandCap WAND_CAP_THAUMIUM;
    public static WandCap WAND_CAP_VOID;
    public static WandRod WAND_ROD_WOOD;
    public static WandRod WAND_ROD_GREATWOOD;
    public static WandRod WAND_ROD_OBSIDIAN;
    public static WandRod WAND_ROD_BLAZE;
    public static WandRod WAND_ROD_ICE;
    public static WandRod WAND_ROD_QUARTZ;
    public static WandRod WAND_ROD_BONE;
    public static WandRod WAND_ROD_REED;
    public static WandRod WAND_ROD_SILVERWOOD;
    public static StaffRod STAFF_ROD_GREATWOOD;
    public static StaffRod STAFF_ROD_OBSIDIAN;
    public static StaffRod STAFF_ROD_BLAZE;
    public static StaffRod STAFF_ROD_ICE;
    public static StaffRod STAFF_ROD_QUARTZ;
    public static StaffRod STAFF_ROD_BONE;
    public static StaffRod STAFF_ROD_REED;
    public static StaffRod STAFF_ROD_SILVERWOOD;
    public static StaffRod STAFF_ROD_PRIMAL;
    public static Item itemWandCasting;
    public static Item itemWandCap;
    public static Item itemWandRod;
    public static Item itemFocusPouch;
    public static Item itemFocusFire;
    public static Item itemFocusFrost;
    public static Item itemFocusShock;
    public static Item itemFocusTrade;
    public static Item itemFocusExcavation;
    public static Item itemFocusHellbat;
    public static Item itemFocusWarding;
    public static Item itemFocusPrimal;
    public static Item itemEssence;
    public static Item itemWispEssence;
    public static Item itemCrystalEssence;
    public static Item itemResource;
    public static Item itemShard;
    public static Item itemNugget;
    public static Item itemNuggetChicken;
    public static Item itemNuggetBeef;
    public static Item itemNuggetPork;
    public static Item itemNuggetFish;
    public static Item itemTripleMeatTreat;
    public static Item itemPhotoPlate;
    public static Item itemManaBean;
    public static Item itemZombieBrain;
    public static Item itemResearchNotes;
    public static Item itemInkwell;
    public static Item itemThaumonomicon;
    public static Item itemSpawnerEgg;
    public static Item itemFocusPortableHole;
    public static Item itemFocusPech;
    public static Item itemThaumometer;
    public static Item itemFlyingCarpet;
    public static Item itemGolemPlacer;
    public static Item itemGolemBell;
    public static Item itemGolemDecoration;
    public static Item itemGolemCore;
    public static Item itemGolemUpgrade;
    public static Item itemArcaneDoor;
    public static Item itemJarFilled;
    public static Item itemJarNode;
    public static Item itemKey;
    public static Item itemHandMirror;
    public static Item itemTrunkSpawner;
    public static Item itemResonator;
    public static Item itemBathSalts;
    public static Item itemBucketDeath;
    public static Item itemBucketPure;
    public static Item itemEldritchObject;
    public static Item itemSanitySoap;
    public static Item itemSanityChecker;
    public static Item itemBottleTaint;
    public static Item itemGoggles;
    public static Item itemBootsTraveller;
    public static Item itemHelmetThaumium;
    public static Item itemChestThaumium;
    public static Item itemBootsThaumium;
    public static Item itemLegsThaumium;
    public static Item itemShovelThaumium;
    public static Item itemShovelElemental;
    public static Item itemPickThaumium;
    public static Item itemPickElemental;
    public static Item itemSwordThaumium;
    public static Item itemSwordElemental;
    public static Item itemAxeThaumium;
    public static Item itemAxeElemental;
    public static Item itemHoeThaumium;
    public static Item itemHoeElemental;
    public static Item itemHelmetFortress;
    public static Item itemChestFortress;
    public static Item itemBootsFortress;
    public static Item itemLegsFortress;
    public static Item itemHelmetVoid;
    public static Item itemChestVoid;
    public static Item itemBootsVoid;
    public static Item itemLegsVoid;
    public static Item itemShovelVoid;
    public static Item itemPickVoid;
    public static Item itemSwordVoid;
    public static Item itemSwordCrimson;
    public static Item itemAxeVoid;
    public static Item itemHoeVoid;
    public static Item itemHelmetVoidRobe;
    public static Item itemChestVoidRobe;
    public static Item itemLegsVoidRobe;
    public static Item itemHelmetCultistRobe;
    public static Item itemChestCultistRobe;
    public static Item itemLegsCultistRobe;
    public static Item itemBootsCultist;
    public static Item itemHelmetCultistPlate;
    public static Item itemChestCultistPlate;
    public static Item itemLegsCultistPlate;
    public static Item itemHelmetCultistLeaderPlate;
    public static Item itemChestCultistLeaderPlate;
    public static Item itemLegsCultistLeaderPlate;
    public static Item itemLootbag;
    public static Item itemBaubleBlanks;
    public static Item itemAmuletRunic;
    public static Item itemRingRunic;
    public static Item itemGirdleRunic;
    public static Item itemGirdleHover;
    public static Item itemAmuletVis;
    public static Item itemLegsRobe;
    public static Item itemChestRobe;
    public static Item itemBootsRobe;
    public static Item itemHoverHarness;
    public static Item itemBowBone;
    public static Item itemPrimalArrow;
    public static Item itemCompassStone;
    public static Item itemPrimalCrusher;

    public static void init() {
        ConfigItems.initializeItems();
        OreDictionary.registerOre((String)"oreCinnabar", (ItemStack)new ItemStack(ConfigBlocks.blockCustomOre, 1, 0));
        OreDictionary.registerOre((String)"oreInfusedAir", (ItemStack)new ItemStack(ConfigBlocks.blockCustomOre, 1, 1));
        OreDictionary.registerOre((String)"oreInfusedFire", (ItemStack)new ItemStack(ConfigBlocks.blockCustomOre, 1, 2));
        OreDictionary.registerOre((String)"oreInfusedWater", (ItemStack)new ItemStack(ConfigBlocks.blockCustomOre, 1, 3));
        OreDictionary.registerOre((String)"oreInfusedEarth", (ItemStack)new ItemStack(ConfigBlocks.blockCustomOre, 1, 4));
        OreDictionary.registerOre((String)"oreInfusedOrder", (ItemStack)new ItemStack(ConfigBlocks.blockCustomOre, 1, 5));
        OreDictionary.registerOre((String)"oreInfusedEntropy", (ItemStack)new ItemStack(ConfigBlocks.blockCustomOre, 1, 6));
        OreDictionary.registerOre((String)"shardAir", (ItemStack)new ItemStack(itemShard, 1, 0));
        OreDictionary.registerOre((String)"shardFire", (ItemStack)new ItemStack(itemShard, 1, 1));
        OreDictionary.registerOre((String)"shardWater", (ItemStack)new ItemStack(itemShard, 1, 2));
        OreDictionary.registerOre((String)"shardEarth", (ItemStack)new ItemStack(itemShard, 1, 3));
        OreDictionary.registerOre((String)"shardOrder", (ItemStack)new ItemStack(itemShard, 1, 4));
        OreDictionary.registerOre((String)"shardEntropy", (ItemStack)new ItemStack(itemShard, 1, 5));
        OreDictionary.registerOre((String)"oreAmber", (ItemStack)new ItemStack(ConfigBlocks.blockCustomOre, 1, 7));
        OreDictionary.registerOre((String)"quicksilver", (ItemStack)new ItemStack(itemResource, 1, 3));
        OreDictionary.registerOre((String)"gemAmber", (ItemStack)new ItemStack(itemResource, 1, 6));
        OreDictionary.registerOre((String)"nuggetIron", (ItemStack)new ItemStack(itemNugget, 1, 0));
        OreDictionary.registerOre((String)"nuggetCopper", (ItemStack)new ItemStack(itemNugget, 1, 1));
        OreDictionary.registerOre((String)"nuggetTin", (ItemStack)new ItemStack(itemNugget, 1, 2));
        OreDictionary.registerOre((String)"nuggetSilver", (ItemStack)new ItemStack(itemNugget, 1, 3));
        OreDictionary.registerOre((String)"nuggetLead", (ItemStack)new ItemStack(itemNugget, 1, 4));
        OreDictionary.registerOre((String)"nuggetThaumium", (ItemStack)new ItemStack(itemNugget, 1, 6));
        OreDictionary.registerOre((String)"nuggetVoid", (ItemStack)new ItemStack(itemNugget, 1, 7));
        OreDictionary.registerOre((String)"nuggetQuicksilver", (ItemStack)new ItemStack(itemResource, 1, 3));
        OreDictionary.registerOre((String)"nuggetGold", (ItemStack)new ItemStack(itemResource, 1, 18));
        OreDictionary.registerOre((String)"ingotThaumium", (ItemStack)new ItemStack(itemResource, 1, 2));
        OreDictionary.registerOre((String)"ingotVoid", (ItemStack)new ItemStack(itemResource, 1, 16));
        OreDictionary.registerOre((String)"clusterIron", (ItemStack)new ItemStack(itemNugget, 1, 16));
        OreDictionary.registerOre((String)"clusterCopper", (ItemStack)new ItemStack(itemNugget, 1, 17));
        OreDictionary.registerOre((String)"clusterTin", (ItemStack)new ItemStack(itemNugget, 1, 18));
        OreDictionary.registerOre((String)"clusterSilver", (ItemStack)new ItemStack(itemNugget, 1, 19));
        OreDictionary.registerOre((String)"clusterLead", (ItemStack)new ItemStack(itemNugget, 1, 20));
        OreDictionary.registerOre((String)"clusterCinnabar", (ItemStack)new ItemStack(itemNugget, 1, 21));
        OreDictionary.registerOre((String)"clusterGold", (ItemStack)new ItemStack(itemNugget, 1, 31));
        OreDictionary.registerOre((String)"logWood", (ItemStack)new ItemStack(ConfigBlocks.blockMagicalLog, 1, 0));
        OreDictionary.registerOre((String)"logWood", (ItemStack)new ItemStack(ConfigBlocks.blockMagicalLog, 1, 1));
        OreDictionary.registerOre((String)"plankWood", (ItemStack)new ItemStack(ConfigBlocks.blockWoodenDevice, 1, 6));
        OreDictionary.registerOre((String)"plankWood", (ItemStack)new ItemStack(ConfigBlocks.blockWoodenDevice, 1, 7));
        OreDictionary.registerOre((String)"slabWood", (ItemStack)new ItemStack(ConfigBlocks.blockSlabWood, 1, 0));
        OreDictionary.registerOre((String)"slabWood", (ItemStack)new ItemStack(ConfigBlocks.blockSlabWood, 1, 1));
        OreDictionary.registerOre((String)"treeSapling", (ItemStack)new ItemStack(ConfigBlocks.blockCustomPlant, 1, 0));
        OreDictionary.registerOre((String)"treeSapling", (ItemStack)new ItemStack(ConfigBlocks.blockCustomPlant, 1, 1));
        WAND_CAP_IRON = new WandCap("iron", 1.1f, new ItemStack(itemWandCap, 1, 0), 1);
        WAND_CAP_GOLD = new WandCap("gold", 1.0f, new ItemStack(itemWandCap, 1, 1), 3);
        WAND_CAP_THAUMIUM = new WandCap("thaumium", 0.9f, new ItemStack(itemWandCap, 1, 2), 6);
        WAND_CAP_VOID = new WandCap("void", 0.8f, new ItemStack(itemWandCap, 1, 7), 9);
        WAND_ROD_WOOD = new WandRod("wood", 25, new ItemStack(Items.field_151055_y), 1);
        WAND_ROD_GREATWOOD = new WandRod("greatwood", 50, new ItemStack(itemWandRod, 1, 0), 3);
        WAND_ROD_OBSIDIAN = new WandRod("obsidian", 75, new ItemStack(itemWandRod, 1, 1), 6, new WandRodPrimalOnUpdate(Aspect.EARTH));
        WAND_ROD_BLAZE = new WandRod("blaze", 75, new ItemStack(itemWandRod, 1, 6), 6, new WandRodPrimalOnUpdate(Aspect.FIRE));
        WAND_ROD_ICE = new WandRod("ice", 75, new ItemStack(itemWandRod, 1, 3), 6, new WandRodPrimalOnUpdate(Aspect.WATER));
        WAND_ROD_QUARTZ = new WandRod("quartz", 75, new ItemStack(itemWandRod, 1, 4), 6, new WandRodPrimalOnUpdate(Aspect.ORDER));
        WAND_ROD_BONE = new WandRod("bone", 75, new ItemStack(itemWandRod, 1, 7), 6, new WandRodPrimalOnUpdate(Aspect.ENTROPY));
        WAND_ROD_REED = new WandRod("reed", 75, new ItemStack(itemWandRod, 1, 5), 6, new WandRodPrimalOnUpdate(Aspect.AIR));
        WAND_ROD_SILVERWOOD = new WandRod("silverwood", 100, new ItemStack(itemWandRod, 1, 2), 9);
        WAND_ROD_BLAZE.setGlowing(true);
        STAFF_ROD_GREATWOOD = new StaffRod("greatwood", 125, new ItemStack(itemWandRod, 1, 50), 8);
        STAFF_ROD_OBSIDIAN = new StaffRod("obsidian", 175, new ItemStack(itemWandRod, 1, 51), 14, new WandRodPrimalOnUpdate(Aspect.EARTH));
        STAFF_ROD_BLAZE = new StaffRod("blaze", 175, new ItemStack(itemWandRod, 1, 56), 14, new WandRodPrimalOnUpdate(Aspect.FIRE));
        STAFF_ROD_ICE = new StaffRod("ice", 175, new ItemStack(itemWandRod, 1, 53), 14, new WandRodPrimalOnUpdate(Aspect.WATER));
        STAFF_ROD_QUARTZ = new StaffRod("quartz", 175, new ItemStack(itemWandRod, 1, 54), 14, new WandRodPrimalOnUpdate(Aspect.ORDER));
        STAFF_ROD_BONE = new StaffRod("bone", 175, new ItemStack(itemWandRod, 1, 57), 14, new WandRodPrimalOnUpdate(Aspect.ENTROPY));
        STAFF_ROD_REED = new StaffRod("reed", 175, new ItemStack(itemWandRod, 1, 55), 14, new WandRodPrimalOnUpdate(Aspect.AIR));
        STAFF_ROD_SILVERWOOD = new StaffRod("silverwood", 250, new ItemStack(itemWandRod, 1, 52), 24);
        STAFF_ROD_PRIMAL = new StaffRod("primal", 250, new ItemStack(itemWandRod, 1, 100), 32, new WandRodPrimalOnUpdate());
        STAFF_ROD_PRIMAL.setRunes(true);
        STAFF_ROD_BLAZE.setGlowing(true);
    }

    public static void postInit() {
        if (Config.foundCopperIngot) {
            WAND_CAP_COPPER = new WandCap("copper", 1.1f, Arrays.asList(Aspect.ORDER, Aspect.ENTROPY), 1.0f, new ItemStack(itemWandCap, 1, 3), 2);
        }
        if (Config.foundSilverIngot) {
            WAND_CAP_SILVER = new WandCap("silver", 1.0f, Arrays.asList(Aspect.AIR, Aspect.EARTH, Aspect.FIRE, Aspect.WATER), 0.95f, new ItemStack(itemWandCap, 1, 4), 4);
        }
    }

    private static void initializeItems() {
        itemWandCasting = new ItemWandCasting().func_77655_b("WandCasting");
        GameRegistry.registerItem((Item)itemWandCasting, (String)"WandCasting", (String)"Thaumcraft");
        itemWandCap = new ItemWandCap().func_77655_b("WandCap");
        GameRegistry.registerItem((Item)itemWandCap, (String)"WandCap", (String)"Thaumcraft");
        itemWandRod = new ItemWandRod().func_77655_b("WandRod");
        GameRegistry.registerItem((Item)itemWandRod, (String)"WandRod", (String)"Thaumcraft");
        itemFocusPouch = new ItemFocusPouchBauble().func_77655_b("FocusPouch");
        GameRegistry.registerItem((Item)itemFocusPouch, (String)"FocusPouch", (String)"Thaumcraft");
        itemFocusFire = new ItemFocusFire().func_77655_b("FocusFire");
        GameRegistry.registerItem((Item)itemFocusFire, (String)"FocusFire", (String)"Thaumcraft");
        itemFocusShock = new ItemFocusShock().func_77655_b("FocusShock");
        GameRegistry.registerItem((Item)itemFocusShock, (String)"FocusShock", (String)"Thaumcraft");
        itemFocusHellbat = new ItemFocusHellbat().func_77655_b("FocusHellbat");
        GameRegistry.registerItem((Item)itemFocusHellbat, (String)"FocusHellbat", (String)"Thaumcraft");
        itemFocusFrost = new ItemFocusFrost().func_77655_b("FocusFrost");
        GameRegistry.registerItem((Item)itemFocusFrost, (String)"FocusFrost", (String)"Thaumcraft");
        itemFocusTrade = new ItemFocusTrade().func_77655_b("FocusTrade");
        GameRegistry.registerItem((Item)itemFocusTrade, (String)"FocusTrade", (String)"Thaumcraft");
        itemFocusExcavation = new ItemFocusExcavation().func_77655_b("FocusExcavation");
        GameRegistry.registerItem((Item)itemFocusExcavation, (String)"FocusExcavation", (String)"Thaumcraft");
        itemFocusPortableHole = new ItemFocusPortableHole().func_77655_b("FocusPortableHole");
        GameRegistry.registerItem((Item)itemFocusPortableHole, (String)"FocusPortableHole", (String)"Thaumcraft");
        itemFocusPech = new ItemFocusPech().func_77655_b("FocusPech");
        GameRegistry.registerItem((Item)itemFocusPech, (String)"FocusPech", (String)"Thaumcraft");
        itemFocusWarding = new ItemFocusWarding().func_77655_b("FocusWarding");
        GameRegistry.registerItem((Item)itemFocusWarding, (String)"FocusWarding", (String)"Thaumcraft");
        itemFocusPrimal = new ItemFocusPrimal().func_77655_b("FocusPrimal");
        GameRegistry.registerItem((Item)itemFocusPrimal, (String)"FocusPrimal", (String)"Thaumcraft");
        itemEssence = new ItemEssence().func_77655_b("ItemEssence");
        GameRegistry.registerItem((Item)itemEssence, (String)"ItemEssence", (String)"Thaumcraft");
        itemManaBean = new ItemManaBean().func_77655_b("ItemManaBean");
        GameRegistry.registerItem((Item)itemManaBean, (String)"ItemManaBean", (String)"Thaumcraft");
        itemWispEssence = new ItemWispEssence().func_77655_b("ItemWispEssence");
        GameRegistry.registerItem((Item)itemWispEssence, (String)"ItemWispEssence", (String)"Thaumcraft");
        itemResource = new ItemResource().func_77655_b("ItemResource");
        GameRegistry.registerItem((Item)itemResource, (String)"ItemResource", (String)"Thaumcraft");
        itemShard = new ItemShard().func_77655_b("ItemShard");
        GameRegistry.registerItem((Item)itemShard, (String)"ItemShard", (String)"Thaumcraft");
        itemResearchNotes = new ItemResearchNotes().func_77655_b("ItemResearchNotes");
        GameRegistry.registerItem((Item)itemResearchNotes, (String)"ItemResearchNotes", (String)"Thaumcraft");
        itemInkwell = new ItemInkwell().func_77655_b("ItemInkwell");
        GameRegistry.registerItem((Item)itemInkwell, (String)"ItemInkwell", (String)"Thaumcraft");
        itemThaumonomicon = new ItemThaumonomicon().func_77655_b("ItemThaumonomicon");
        GameRegistry.registerItem((Item)itemThaumonomicon, (String)"ItemThaumonomicon", (String)"Thaumcraft");
        itemThaumometer = new ItemThaumometer().func_77655_b("ItemThaumometer");
        GameRegistry.registerItem((Item)itemThaumometer, (String)"ItemThaumometer", (String)"Thaumcraft");
        itemGoggles = new ItemGoggles(ThaumcraftApi.armorMatSpecial, 4, 0).func_77655_b("ItemGoggles");
        GameRegistry.registerItem((Item)itemGoggles, (String)"ItemGoggles", (String)"Thaumcraft");
        itemHelmetThaumium = new ItemThaumiumArmor(ThaumcraftApi.armorMatThaumium, 2, 0).func_77655_b("ItemHelmetThaumium");
        GameRegistry.registerItem((Item)itemHelmetThaumium, (String)"ItemHelmetThaumium", (String)"Thaumcraft");
        itemChestThaumium = new ItemThaumiumArmor(ThaumcraftApi.armorMatThaumium, 2, 1).func_77655_b("ItemChestplateThaumium");
        GameRegistry.registerItem((Item)itemChestThaumium, (String)"ItemChestplateThaumium", (String)"Thaumcraft");
        itemLegsThaumium = new ItemThaumiumArmor(ThaumcraftApi.armorMatThaumium, 2, 2).func_77655_b("ItemLeggingsThaumium");
        GameRegistry.registerItem((Item)itemLegsThaumium, (String)"ItemLeggingsThaumium", (String)"Thaumcraft");
        itemBootsThaumium = new ItemThaumiumArmor(ThaumcraftApi.armorMatThaumium, 2, 3).func_77655_b("ItemBootsThaumium");
        GameRegistry.registerItem((Item)itemBootsThaumium, (String)"ItemBootsThaumium", (String)"Thaumcraft");
        itemShovelThaumium = new ItemThaumiumShovel(ThaumcraftApi.toolMatThaumium).func_77655_b("ItemShovelThaumium");
        GameRegistry.registerItem((Item)itemShovelThaumium, (String)"ItemShovelThaumium", (String)"Thaumcraft");
        itemPickThaumium = new ItemThaumiumPickaxe(ThaumcraftApi.toolMatThaumium).func_77655_b("ItemPickThaumium");
        GameRegistry.registerItem((Item)itemPickThaumium, (String)"ItemPickThaumium", (String)"Thaumcraft");
        itemAxeThaumium = new ItemThaumiumAxe(ThaumcraftApi.toolMatThaumium).func_77655_b("ItemAxeThaumium");
        GameRegistry.registerItem((Item)itemAxeThaumium, (String)"ItemAxeThaumium", (String)"Thaumcraft");
        itemSwordThaumium = new ItemThaumiumSword(ThaumcraftApi.toolMatThaumium).func_77655_b("ItemSwordThaumium");
        GameRegistry.registerItem((Item)itemSwordThaumium, (String)"ItemSwordThaumium", (String)"Thaumcraft");
        itemHoeThaumium = new ItemThaumiumHoe(ThaumcraftApi.toolMatThaumium).func_77655_b("ItemHoeThaumium");
        GameRegistry.registerItem((Item)itemHoeThaumium, (String)"ItemHoeThaumium", (String)"Thaumcraft");
        itemArcaneDoor = new ItemArcaneDoor().func_77655_b("ItemArcaneDoor");
        GameRegistry.registerItem((Item)itemArcaneDoor, (String)"ItemArcaneDoor", (String)"Thaumcraft");
        itemNugget = new ItemNugget().func_77655_b("ItemNugget");
        GameRegistry.registerItem((Item)itemNugget, (String)"ItemNugget", (String)"Thaumcraft");
        itemBootsTraveller = new ItemBootsTraveller(ThaumcraftApi.armorMatSpecial, 4, 3).func_77655_b("BootsTraveller");
        GameRegistry.registerItem((Item)itemBootsTraveller, (String)"BootsTraveller", (String)"Thaumcraft");
        itemNuggetChicken = new ItemNuggetEdible("nuggetchicken").func_77655_b("ItemNuggetChicken");
        GameRegistry.registerItem((Item)itemNuggetChicken, (String)"ItemNuggetChicken", (String)"Thaumcraft");
        itemNuggetBeef = new ItemNuggetEdible("nuggetbeef").func_77655_b("ItemNuggetBeef");
        GameRegistry.registerItem((Item)itemNuggetBeef, (String)"ItemNuggetBeef", (String)"Thaumcraft");
        itemNuggetPork = new ItemNuggetEdible("nuggetpork").func_77655_b("ItemNuggetPork");
        GameRegistry.registerItem((Item)itemNuggetPork, (String)"ItemNuggetPork", (String)"Thaumcraft");
        itemNuggetFish = new ItemNuggetEdible("nuggetfish").func_77655_b("ItemNuggetFish");
        GameRegistry.registerItem((Item)itemNuggetFish, (String)"ItemNuggetFish", (String)"Thaumcraft");
        itemTripleMeatTreat = new ItemTripleMeatTreat().func_77655_b("TripleMeatTreat");
        GameRegistry.registerItem((Item)itemTripleMeatTreat, (String)"TripleMeatTreat", (String)"Thaumcraft");
        itemSwordElemental = new ItemElementalSword(ThaumcraftApi.toolMatElemental).func_77655_b("ItemSwordElemental");
        GameRegistry.registerItem((Item)itemSwordElemental, (String)"ItemSwordElemental", (String)"Thaumcraft");
        itemShovelElemental = new ItemElementalShovel(ThaumcraftApi.toolMatElemental).func_77655_b("ItemShovelElemental");
        GameRegistry.registerItem((Item)itemShovelElemental, (String)"ItemShovelElemental", (String)"Thaumcraft");
        itemPickElemental = new ItemElementalPickaxe(ThaumcraftApi.toolMatElemental).func_77655_b("ItemPickaxeElemental");
        GameRegistry.registerItem((Item)itemPickElemental, (String)"ItemPickaxeElemental", (String)"Thaumcraft");
        itemAxeElemental = new ItemElementalAxe(ThaumcraftApi.toolMatElemental).func_77655_b("ItemAxeElemental");
        GameRegistry.registerItem((Item)itemAxeElemental, (String)"ItemAxeElemental", (String)"Thaumcraft");
        itemHoeElemental = new ItemElementalHoe(ThaumcraftApi.toolMatElemental).func_77655_b("ItemHoeElemental");
        GameRegistry.registerItem((Item)itemHoeElemental, (String)"ItemHoeElemental", (String)"Thaumcraft");
        itemChestRobe = new ItemRobeArmor(ThaumcraftApi.armorMatSpecial, 1, 1).func_77655_b("ItemChestplateRobe");
        GameRegistry.registerItem((Item)itemChestRobe, (String)"ItemChestplateRobe", (String)"Thaumcraft");
        itemLegsRobe = new ItemRobeArmor(ThaumcraftApi.armorMatSpecial, 2, 2).func_77655_b("ItemLeggingsRobe");
        GameRegistry.registerItem((Item)itemLegsRobe, (String)"ItemLeggingsRobe", (String)"Thaumcraft");
        itemBootsRobe = new ItemRobeArmor(ThaumcraftApi.armorMatSpecial, 1, 3).func_77655_b("ItemBootsRobe");
        GameRegistry.registerItem((Item)itemBootsRobe, (String)"ItemBootsRobe", (String)"Thaumcraft");
        itemKey = new ItemKey().func_77655_b("ArcaneDoorKey");
        GameRegistry.registerItem((Item)itemKey, (String)"ArcaneDoorKey", (String)"Thaumcraft");
        itemHandMirror = new ItemHandMirror().func_77655_b("HandMirror");
        GameRegistry.registerItem((Item)itemHandMirror, (String)"HandMirror", (String)"Thaumcraft");
        itemHoverHarness = new ItemHoverHarness(ThaumcraftApi.armorMatSpecial, 1, 1).func_77655_b("HoverHarness");
        GameRegistry.registerItem((Item)itemHoverHarness, (String)"HoverHarness", (String)"Thaumcraft");
        itemJarFilled = new ItemJarFilled().func_77655_b("BlockJarFilledItem");
        GameRegistry.registerItem((Item)itemJarFilled, (String)"BlockJarFilledItem", (String)"Thaumcraft");
        itemJarNode = new ItemJarNode().func_77655_b("BlockJarNodeItem");
        GameRegistry.registerItem((Item)itemJarNode, (String)"BlockJarNodeItem", (String)"Thaumcraft");
        itemTrunkSpawner = new ItemTrunkSpawner().func_77655_b("TrunkSpawner");
        GameRegistry.registerItem((Item)itemTrunkSpawner, (String)"TrunkSpawner", (String)"Thaumcraft");
        itemGolemPlacer = new ItemGolemPlacer().func_77655_b("ItemGolemPlacer");
        GameRegistry.registerItem((Item)itemGolemPlacer, (String)"ItemGolemPlacer", (String)"Thaumcraft");
        itemGolemCore = new ItemGolemCore().func_77655_b("ItemGolemCore");
        GameRegistry.registerItem((Item)itemGolemCore, (String)"ItemGolemCore", (String)"Thaumcraft");
        itemGolemUpgrade = new ItemGolemUpgrade().func_77655_b("ItemGolemUpgrade");
        GameRegistry.registerItem((Item)itemGolemUpgrade, (String)"ItemGolemUpgrade", (String)"Thaumcraft");
        itemGolemBell = new ItemGolemBell().func_77655_b("GolemBell");
        GameRegistry.registerItem((Item)itemGolemBell, (String)"GolemBell", (String)"Thaumcraft");
        itemGolemDecoration = new ItemGolemDecoration().func_77655_b("ItemGolemDecoration");
        GameRegistry.registerItem((Item)itemGolemDecoration, (String)"ItemGolemDecoration", (String)"Thaumcraft");
        itemBowBone = new ItemBowBone().func_77655_b("ItemBowBone");
        GameRegistry.registerItem((Item)itemBowBone, (String)"ItemBowBone", (String)"Thaumcraft");
        itemPrimalArrow = new ItemPrimalArrow().func_77655_b("ItemPrimalArrow");
        GameRegistry.registerItem((Item)itemPrimalArrow, (String)"PrimalArrow", (String)"Thaumcraft");
        itemResonator = new ItemResonator().func_77655_b("ItemResonator");
        GameRegistry.registerItem((Item)itemResonator, (String)"ItemResonator", (String)"Thaumcraft");
        itemBaubleBlanks = new ItemBaubleBlanks().func_77655_b("ItemBaubleBlanks");
        GameRegistry.registerItem((Item)itemBaubleBlanks, (String)"ItemBaubleBlanks", (String)"Thaumcraft");
        itemAmuletRunic = new ItemAmuletRunic().func_77655_b("ItemAmuletRunic");
        GameRegistry.registerItem((Item)itemAmuletRunic, (String)"ItemAmuletRunic", (String)"Thaumcraft");
        itemRingRunic = new ItemRingRunic().func_77655_b("ItemRingRunic");
        GameRegistry.registerItem((Item)itemRingRunic, (String)"ItemRingRunic", (String)"Thaumcraft");
        itemGirdleRunic = new ItemGirdleRunic().func_77655_b("ItemGirdleRunic");
        GameRegistry.registerItem((Item)itemGirdleRunic, (String)"ItemGirdleRunic", (String)"Thaumcraft");
        itemAmuletVis = new ItemAmuletVis().func_77655_b("ItemAmuletVis");
        GameRegistry.registerItem((Item)itemAmuletVis, (String)"ItemAmuletVis", (String)"Thaumcraft");
        itemGirdleHover = new ItemGirdleHover().func_77655_b("ItemGirdleHover");
        GameRegistry.registerItem((Item)itemGirdleHover, (String)"ItemGirdleHover", (String)"Thaumcraft");
        itemSpawnerEgg = new ItemSpawnerEgg().func_77655_b("ItemSpawnerEgg");
        GameRegistry.registerItem((Item)itemSpawnerEgg, (String)"ItemSpawnerEgg", (String)"Thaumcraft");
        itemZombieBrain = new ItemZombieBrain().func_77655_b("ItemZombieBrain");
        GameRegistry.registerItem((Item)itemZombieBrain, (String)"ItemZombieBrain", (String)"Thaumcraft");
        itemBathSalts = new ItemBathSalts().func_77655_b("ItemBathSalts");
        GameRegistry.registerItem((Item)itemBathSalts, (String)"ItemBathSalts", (String)"Thaumcraft");
        itemCrystalEssence = new ItemCrystalEssence().func_77655_b("ItemCrystalEssence");
        GameRegistry.registerItem((Item)itemCrystalEssence, (String)"ItemCrystalEssence", (String)"Thaumcraft");
        itemBucketDeath = new ItemBucketDeath().func_77655_b("ItemBucketDeath");
        GameRegistry.registerItem((Item)itemBucketDeath, (String)"ItemBucketDeath", (String)"Thaumcraft");
        itemBucketPure = new ItemBucketPure().func_77655_b("ItemBucketPure");
        GameRegistry.registerItem((Item)itemBucketPure, (String)"ItemBucketPure", (String)"Thaumcraft");
        FluidContainerRegistry.registerFluidContainer((FluidStack)new FluidStack(ConfigBlocks.FLUIDDEATH, 1000), (ItemStack)new ItemStack(itemBucketDeath), (ItemStack)new ItemStack(Items.field_151133_ar));
        FluidContainerRegistry.registerFluidContainer((FluidStack)new FluidStack(ConfigBlocks.FLUIDPURE, 1000), (ItemStack)new ItemStack(itemBucketPure), (ItemStack)new ItemStack(Items.field_151133_ar));
        itemHelmetFortress = new ItemFortressArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 0).func_77655_b("ItemHelmetFortress");
        GameRegistry.registerItem((Item)itemHelmetFortress, (String)"ItemHelmetFortress", (String)"Thaumcraft");
        itemChestFortress = new ItemFortressArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 1).func_77655_b("ItemChestplateFortress");
        GameRegistry.registerItem((Item)itemChestFortress, (String)"ItemChestplateFortress", (String)"Thaumcraft");
        itemLegsFortress = new ItemFortressArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 2).func_77655_b("ItemLeggingsFortress");
        GameRegistry.registerItem((Item)itemLegsFortress, (String)"ItemLeggingsFortress", (String)"Thaumcraft");
        itemEldritchObject = new ItemEldritchObject().func_77655_b("ItemEldritchObject");
        GameRegistry.registerItem((Item)itemEldritchObject, (String)"ItemEldritchObject", (String)"Thaumcraft");
        itemHelmetVoid = new ItemVoidArmor(ThaumcraftApi.armorMatVoid, 2, 0).func_77655_b("ItemHelmetVoid");
        GameRegistry.registerItem((Item)itemHelmetVoid, (String)"ItemHelmetVoid", (String)"Thaumcraft");
        itemChestVoid = new ItemVoidArmor(ThaumcraftApi.armorMatVoid, 2, 1).func_77655_b("ItemChestplateVoid");
        GameRegistry.registerItem((Item)itemChestVoid, (String)"ItemChestplateVoid", (String)"Thaumcraft");
        itemLegsVoid = new ItemVoidArmor(ThaumcraftApi.armorMatVoid, 2, 2).func_77655_b("ItemLeggingsVoid");
        GameRegistry.registerItem((Item)itemLegsVoid, (String)"ItemLeggingsVoid", (String)"Thaumcraft");
        itemBootsVoid = new ItemVoidArmor(ThaumcraftApi.armorMatVoid, 2, 3).func_77655_b("ItemBootsVoid");
        GameRegistry.registerItem((Item)itemBootsVoid, (String)"ItemBootsVoid", (String)"Thaumcraft");
        itemShovelVoid = new ItemVoidShovel(ThaumcraftApi.toolMatVoid).func_77655_b("ItemShovelVoid");
        GameRegistry.registerItem((Item)itemShovelVoid, (String)"ItemShovelVoid", (String)"Thaumcraft");
        itemPickVoid = new ItemVoidPickaxe(ThaumcraftApi.toolMatVoid).func_77655_b("ItemPickVoid");
        GameRegistry.registerItem((Item)itemPickVoid, (String)"ItemPickVoid", (String)"Thaumcraft");
        itemAxeVoid = new ItemVoidAxe(ThaumcraftApi.toolMatVoid).func_77655_b("ItemAxeVoid");
        GameRegistry.registerItem((Item)itemAxeVoid, (String)"ItemAxeVoid", (String)"Thaumcraft");
        itemSwordVoid = new ItemVoidSword(ThaumcraftApi.toolMatVoid).func_77655_b("ItemSwordVoid");
        GameRegistry.registerItem((Item)itemSwordVoid, (String)"ItemSwordVoid", (String)"Thaumcraft");
        itemHoeVoid = new ItemVoidHoe(ThaumcraftApi.toolMatVoid).func_77655_b("ItemHoeVoid");
        GameRegistry.registerItem((Item)itemHoeVoid, (String)"ItemHoeVoid", (String)"Thaumcraft");
        itemHelmetVoidRobe = new ItemVoidRobeArmor(ThaumcraftApi.armorMatVoid, 4, 0).func_77655_b("ItemHelmetVoidRobe");
        GameRegistry.registerItem((Item)itemHelmetVoidRobe, (String)"ItemHelmetVoidFortress", (String)"Thaumcraft");
        itemChestVoidRobe = new ItemVoidRobeArmor(ThaumcraftApi.armorMatVoid, 4, 1).func_77655_b("ItemChestplateVoidRobe");
        GameRegistry.registerItem((Item)itemChestVoidRobe, (String)"ItemChestplateVoidFortress", (String)"Thaumcraft");
        itemLegsVoidRobe = new ItemVoidRobeArmor(ThaumcraftApi.armorMatVoid, 4, 2).func_77655_b("ItemLeggingsVoidRobe");
        GameRegistry.registerItem((Item)itemLegsVoidRobe, (String)"ItemLeggingsVoidFortress", (String)"Thaumcraft");
        itemSanitySoap = new ItemSanitySoap().func_77655_b("ItemSanitySoap");
        GameRegistry.registerItem((Item)itemSanitySoap, (String)"ItemSanitySoap", (String)"Thaumcraft");
        itemSanityChecker = new ItemSanityChecker().func_77655_b("ItemSanityChecker");
        GameRegistry.registerItem((Item)itemSanityChecker, (String)"ItemSanityChecker", (String)"Thaumcraft");
        itemBottleTaint = new ItemBottleTaint().func_77655_b("ItemBottleTaint");
        GameRegistry.registerItem((Item)itemBottleTaint, (String)"ItemBottleTaint", (String)"Thaumcraft");
        itemHelmetCultistRobe = new ItemCultistRobeArmor(ItemArmor.ArmorMaterial.IRON, 4, 0).func_77655_b("ItemHelmetCultistRobe");
        GameRegistry.registerItem((Item)itemHelmetCultistRobe, (String)"ItemHelmetCultistRobe", (String)"Thaumcraft");
        itemChestCultistRobe = new ItemCultistRobeArmor(ItemArmor.ArmorMaterial.IRON, 4, 1).func_77655_b("ItemChestplateCultistRobe");
        GameRegistry.registerItem((Item)itemChestCultistRobe, (String)"ItemChestplateCultistRobe", (String)"Thaumcraft");
        itemLegsCultistRobe = new ItemCultistRobeArmor(ItemArmor.ArmorMaterial.IRON, 4, 2).func_77655_b("ItemLeggingsCultistRobe");
        GameRegistry.registerItem((Item)itemLegsCultistRobe, (String)"ItemLeggingsCultistRobe", (String)"Thaumcraft");
        itemBootsCultist = new ItemCultistBoots(ItemArmor.ArmorMaterial.IRON, 4, 3).func_77655_b("ItemBootsCultist");
        GameRegistry.registerItem((Item)itemBootsCultist, (String)"ItemBootsCultist", (String)"Thaumcraft");
        itemHelmetCultistPlate = new ItemCultistPlateArmor(ItemArmor.ArmorMaterial.IRON, 4, 0).func_77655_b("ItemHelmetCultistPlate");
        GameRegistry.registerItem((Item)itemHelmetCultistPlate, (String)"ItemHelmetCultistPlate", (String)"Thaumcraft");
        itemChestCultistPlate = new ItemCultistPlateArmor(ItemArmor.ArmorMaterial.IRON, 4, 1).func_77655_b("ItemChestplateCultistPlate");
        GameRegistry.registerItem((Item)itemChestCultistPlate, (String)"ItemChestplateCultistPlate", (String)"Thaumcraft");
        itemLegsCultistPlate = new ItemCultistPlateArmor(ItemArmor.ArmorMaterial.IRON, 4, 2).func_77655_b("ItemLeggingsCultistPlate");
        GameRegistry.registerItem((Item)itemLegsCultistPlate, (String)"ItemLeggingsCultistPlate", (String)"Thaumcraft");
        itemHelmetCultistLeaderPlate = new ItemCultistLeaderArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 0).func_77655_b("ItemHelmetCultistLeaderPlate");
        GameRegistry.registerItem((Item)itemHelmetCultistLeaderPlate, (String)"ItemHelmetCultistLeaderPlate", (String)"Thaumcraft");
        itemChestCultistLeaderPlate = new ItemCultistLeaderArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 1).func_77655_b("ItemChestplateCultistLeaderPlate");
        GameRegistry.registerItem((Item)itemChestCultistLeaderPlate, (String)"ItemChestplateCultistLeaderPlate", (String)"Thaumcraft");
        itemLegsCultistLeaderPlate = new ItemCultistLeaderArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 2).func_77655_b("ItemLeggingsCultistLeaderPlate");
        GameRegistry.registerItem((Item)itemLegsCultistLeaderPlate, (String)"ItemLeggingsCultistLeaderPlate", (String)"Thaumcraft");
        itemSwordCrimson = new ItemCrimsonSword().func_77655_b("ItemSwordCrimson");
        GameRegistry.registerItem((Item)itemSwordCrimson, (String)"ItemSwordCrimson", (String)"Thaumcraft");
        itemLootbag = new ItemLootBag().func_77655_b("ItemLootBag");
        GameRegistry.registerItem((Item)itemLootbag, (String)"ItemLootBag", (String)"Thaumcraft");
        itemCompassStone = new ItemCompassStone().func_77655_b("ItemCompassStone");
        GameRegistry.registerItem((Item)itemCompassStone, (String)"ItemCompassStone", (String)"Thaumcraft");
        itemPrimalCrusher = new ItemPrimalCrusher(ItemPrimalCrusher.material).func_77655_b("ItemPrimalCrusher");
        GameRegistry.registerItem((Item)itemPrimalCrusher, (String)"ItemPrimalCrusher", (String)"Thaumcraft");
    }
}

