/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.entity.Entity
 *  net.minecraft.nbt.NBTBase
 *  net.minecraft.nbt.NBTTagCompound
 *  net.minecraft.nbt.NBTTagList
 *  net.minecraft.world.World
 *  net.minecraft.world.gen.structure.StructureBoundingBox
 */
package com.emoniph.witchery.worldgen;

import com.emoniph.witchery.entity.EntityGoblin;
import com.emoniph.witchery.worldgen.ComponentClonedStructure;
import java.util.Random;
import net.minecraft.entity.Entity;
import net.minecraft.nbt.NBTBase;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.nbt.NBTTagList;
import net.minecraft.world.World;
import net.minecraft.world.gen.structure.StructureBoundingBox;

public class ComponentGoblinHut
extends ComponentClonedStructure {
    public ComponentGoblinHut() {
    }

    public ComponentGoblinHut(int direction, Random random, int x, int z, int w, int h, int d) {
        super(direction, random, x, z, w, h, d);
    }

    @Override
    protected NBTTagCompound getSchematic(World world, Random random) {
        NBTTagCompound nbtSchematic = new NBTTagCompound();
        NBTTagList nbtList = new NBTTagList();
        NBTTagCompound nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:oak_stairs");
        nbtBlock.func_74768_a("m", 4);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:oak_stairs");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:oak_stairs");
        nbtBlock.func_74768_a("m", 4);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:planks");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 7);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:oak_stairs");
        nbtBlock.func_74768_a("m", 5);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_door");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_door");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 5);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 6);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:planks");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:oak_stairs");
        nbtBlock.func_74768_a("m", 6);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 5);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:stone_slab");
        nbtBlock.func_74768_a("m", 3);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 9);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:stone_slab");
        nbtBlock.func_74768_a("m", 3);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:stone_slab");
        nbtBlock.func_74768_a("m", 3);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 9);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 5);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:oak_stairs");
        nbtBlock.func_74768_a("m", 7);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:planks");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 3);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 2);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 7);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:stone_slab");
        nbtBlock.func_74768_a("m", 3);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 3);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:cauldron");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:stone_slab");
        nbtBlock.func_74768_a("m", 3);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 2);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 6);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:planks");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 2);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:oak_stairs");
        nbtBlock.func_74768_a("m", 6);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:birch_stairs");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 4);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:stone_slab");
        nbtBlock.func_74768_a("m", 3);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 9);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:stone_slab");
        nbtBlock.func_74768_a("m", 3);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:stone_slab");
        nbtBlock.func_74768_a("m", 3);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 9);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 4);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:oak_stairs");
        nbtBlock.func_74768_a("m", 7);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:planks");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 9);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 7);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 9);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 4);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 8);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 9);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:torch");
        nbtBlock.func_74768_a("m", 5);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtBlock.func_74768_a("m", 6);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:planks");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:oak_stairs");
        nbtBlock.func_74768_a("m", 5);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:planks");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:fence");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:spruce_stairs");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:oak_stairs");
        nbtBlock.func_74768_a("m", 5);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:log");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:wooden_slab");
        nbtBlock.func_74768_a("m", 1);
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtBlock = new NBTTagCompound();
        nbtBlock.func_74778_a("n", "minecraft:air");
        nbtList.func_74742_a((NBTBase)nbtBlock);
        nbtSchematic.func_74782_a("blocks", (NBTBase)nbtList);
        nbtSchematic.func_74768_a("xMax", 7);
        nbtSchematic.func_74768_a("yMax", 6);
        nbtSchematic.func_74768_a("zMax", 7);
        return nbtSchematic;
    }

    @Override
    protected void spawnInhabitant(World world, StructureBoundingBox bounds) {
        EntityGoblin goblin = new EntityGoblin(world);
        goblin.func_110163_bv();
        goblin.func_70012_b(bounds.func_78881_e(), bounds.field_78894_e - 4, bounds.func_78891_g(), 0.0f, 0.0f);
        world.func_72838_d((Entity)goblin);
    }
}

