/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.eventbus.EventBus
 *  cpw.mods.fml.common.DummyModContainer
 *  cpw.mods.fml.common.LoadController
 *  cpw.mods.fml.common.ModMetadata
 *  cpw.mods.fml.relauncher.IFMLLoadingPlugin
 *  org.apache.logging.log4j.LogManager
 *  org.apache.logging.log4j.Logger
 */
package thaumic.tinkerer.preloader;

import com.google.common.eventbus.EventBus;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin;
import java.util.Arrays;
import java.util.Map;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class ThaumicTLoaderContainer
extends DummyModContainer
implements IFMLLoadingPlugin {
    public static Logger logger = LogManager.getLogger((String)"TTinkers");
    private final ModMetadata md = new ModMetadata();

    public ThaumicTLoaderContainer() {
        this.md.autogenerated = true;
        this.md.credits = "nekosune, Pixlepix, and all thanks to Vazkii";
        this.md.modId = this.getModId();
        this.md.version = this.getVersion();
        this.md.name = this.getName();
        this.md.authorList = Arrays.asList("nekosune", "Pixlepix", "Vazkii");
    }

    public String getModId() {
        return "ThaumicTinkerer-preloader";
    }

    public String getName() {
        return "Thaumic Tinkerer Core";
    }

    public String getVersion() {
        return "0.1";
    }

    public String getDisplayVersion() {
        return this.getVersion();
    }

    public ModMetadata getMetadata() {
        return this.md;
    }

    public boolean registerBus(EventBus bus, LoadController controller) {
        bus.register((Object)this);
        return true;
    }

    public String[] getASMTransformerClass() {
        return new String[]{"thaumic.tinkerer.preloader.AccessTransformer"};
    }

    public String getModContainerClass() {
        return "thaumic.tinkerer.preloader.ThaumicTLoaderContainer";
    }

    public String getSetupClass() {
        return null;
    }

    public void injectData(Map<String, Object> data) {
    }

    public String getAccessTransformerClass() {
        return "thaumic.tinkerer.preloader.AccessTransformer";
    }
}

