/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.common.event.FMLInterModComms
 *  net.minecraft.block.Block
 *  net.minecraft.entity.EntityLivingBase
 *  net.minecraft.entity.player.EntityPlayer
 *  net.minecraft.item.Item
 *  net.minecraft.item.ItemStack
 *  thaumcraft.api.ThaumcraftApi
 *  thaumcraft.api.ThaumcraftApi$EntityTagsNBT
 *  thaumcraft.api.ThaumcraftApiHelper
 *  thaumcraft.api.aspects.Aspect
 *  thaumcraft.api.aspects.AspectList
 */
package com.emoniph.witchery.integration;

import com.emoniph.witchery.Witchery;
import com.emoniph.witchery.integration.ModHook;
import com.emoniph.witchery.util.Config;
import cpw.mods.fml.common.event.FMLInterModComms;
import net.minecraft.block.Block;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.api.ThaumcraftApiHelper;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;

public class ModHookThaumcraft4
extends ModHook {
    @Override
    public String getModID() {
        return "Thaumcraft";
    }

    @Override
    protected void doInit() {
        FMLInterModComms.sendMessage((String)this.getModID(), (String)"harvestStandardCrop", (ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_ARTICHOKE, 1, Witchery.Blocks.CROP_ARTICHOKE.getNumGrowthStages()));
        FMLInterModComms.sendMessage((String)this.getModID(), (String)"harvestStandardCrop", (ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_BELLADONNA, 1, Witchery.Blocks.CROP_BELLADONNA.getNumGrowthStages()));
        FMLInterModComms.sendMessage((String)this.getModID(), (String)"harvestStandardCrop", (ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_MANDRAKE, 1, Witchery.Blocks.CROP_MANDRAKE.getNumGrowthStages()));
        FMLInterModComms.sendMessage((String)this.getModID(), (String)"harvestStandardCrop", (ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_SNOWBELL, 1, Witchery.Blocks.CROP_SNOWBELL.getNumGrowthStages()));
        FMLInterModComms.sendMessage((String)this.getModID(), (String)"harvestStandardCrop", (ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_WORMWOOD, 1, Witchery.Blocks.CROP_WORMWOOD.getNumGrowthStages()));
        FMLInterModComms.sendMessage((String)this.getModID(), (String)"harvestStandardCrop", (ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_MINDRAKE, 1, Witchery.Blocks.CROP_MINDRAKE.getNumGrowthStages()));
        FMLInterModComms.sendMessage((String)this.getModID(), (String)"harvestStandardCrop", (ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_WOLFSBANE, 1, Witchery.Blocks.CROP_WOLFSBANE.getNumGrowthStages()));
        FMLInterModComms.sendMessage((String)"Thaumcraft", (String)"dimensionBlacklist", (String)("" + Config.instance().dimensionDreamID + ":0"));
        FMLInterModComms.sendMessage((String)"Thaumcraft", (String)"dimensionBlacklist", (String)("" + Config.instance().dimensionTormentID + ":0"));
    }

    @Override
    protected void doPostInit() {
        IntegrateThaumcraft.registerAspects();
    }

    @Override
    protected void doReduceMagicPower(EntityLivingBase entity, float factor) {
        IntegrateThaumcraft.reduceMagicPower(entity, factor);
    }

    private static class IntegrateThaumcraft {
        private IntegrateThaumcraft() {
        }

        public static void reduceMagicPower(EntityLivingBase entity, float percentage) {
            if (entity instanceof EntityPlayer) {
                EntityPlayer player = (EntityPlayer)entity;
                for (Aspect aspect : Aspect.aspects.values()) {
                    int countdown;
                    AspectList list = new AspectList().add(aspect, 100);
                    int n = countdown = percentage == 1.0f ? 1000 : (int)Math.max(150.0f * percentage, 1.0f);
                    while (ThaumcraftApiHelper.consumeVisFromInventory((EntityPlayer)player, (AspectList)list) && countdown > 0) {
                        --countdown;
                    }
                }
            }
        }

        public static void registerAspects() {
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.WICKER_BUNDLE), (int[])new int[]{0, 4, 8}, (AspectList)new AspectList().add(Aspect.TREE, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.WICKER_BUNDLE), (int[])new int[]{1, 5, 9}, (AspectList)new AspectList().add(Aspect.TREE, 2).add(Aspect.FLESH, 2).add(Aspect.DEATH, 3).add(Aspect.FIRE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.STOCKADE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TREE, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.STATUE_OF_WORSHIP), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.EARTH, 3).add(Aspect.MIND, 3).add(Aspect.SOUL, 2).add(Aspect.MAGIC, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.LOG), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TREE, 2).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.PLANKS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TREE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.STAIRS_ALDER), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TREE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.STAIRS_HAWTHORN), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TREE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.STAIRS_ROWAN), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TREE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.SAPLING), (int[])new int[]{0}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.MAGIC, 1).add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.SAPLING), (int[])new int[]{1}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.ENTROPY, 1).add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.SAPLING), (int[])new int[]{2}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.ORDER, 1).add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.LEAVES), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.DOOR_ALDER), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TREE, 2).add(Aspect.MECHANISM, 2).add(Aspect.MOTION, 1).add(Aspect.TRAP, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.DOOR_ROWAN), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TREE, 2).add(Aspect.MECHANISM, 2).add(Aspect.MOTION, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemRowanBerries.damageValue}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.HUNGER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.ALTAR), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MAGIC, 3).add(Aspect.EARTH, 4).add(Aspect.MECHANISM, 3).add(Aspect.ENERGY, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.DISTILLERY_IDLE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MAGIC, 2).add(Aspect.METAL, 8).add(Aspect.MECHANISM, 3).add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 4).add(Aspect.ENERGY, 4).add(Aspect.AIR, 2).add(Aspect.WATER, 2).add(Aspect.FIRE, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.DISTILLERY_BURNING), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MAGIC, 2).add(Aspect.METAL, 8).add(Aspect.MECHANISM, 3).add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 4).add(Aspect.ENERGY, 4).add(Aspect.AIR, 2).add(Aspect.WATER, 2).add(Aspect.FIRE, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.OVEN_IDLE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.METAL, 14).add(Aspect.MECHANISM, 3).add(Aspect.FIRE, 1).add(Aspect.AIR, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.OVEN_BURNING), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.METAL, 14).add(Aspect.MECHANISM, 3).add(Aspect.FIRE, 3).add(Aspect.AIR, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.SPINNING_WHEEL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TREE, 2).add(Aspect.MECHANISM, 3).add(Aspect.CLOTH, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_BELLADONNA), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.POISON, 4).add(Aspect.DEATH, 4).add(Aspect.CROP, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_MANDRAKE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.MAN, 1).add(Aspect.CROP, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_ARTICHOKE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.WATER, 2).add(Aspect.CROP, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_SNOWBELL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.COLD, 2).add(Aspect.CROP, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemSeedsTreefyd.damageValue}, (AspectList)new AspectList().add(Aspect.PLANT, 4).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.SEEDS_BELLADONNA), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.POISON, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.SEEDS_MANDRAKE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.EARTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.SEEDS_ARTICHOKE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.SEEDS_SNOWBELL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.COLD, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Block)Witchery.Blocks.KETTLE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.METAL, 6).add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 4).add(Aspect.ENERGY, 4).add(Aspect.MAGIC, 2).add(Aspect.WATER, 4).add(Aspect.CRAFT, 8));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Block)Witchery.Blocks.CAULDRON), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.METAL, 6).add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 4).add(Aspect.ENERGY, 4).add(Aspect.MAGIC, 2).add(Aspect.WATER, 4).add(Aspect.CRAFT, 8));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.POPPET_SHELF), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CRYSTAL, 6).add(Aspect.GREED, 6).add(Aspect.ENERGY, 4).add(Aspect.MAGIC, 4).add(Aspect.SOUL, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.SPANISH_MOSS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.SOUL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.LEAPING_LILY), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.WATER, 1).add(Aspect.MOTION, 3).add(Aspect.FLIGHT, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.EMBER_MOSS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.FIRE, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.GLINT_WEED), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.FIRE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.GLOW_GLOBE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.FIRE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.ALLURING_SKULL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.DEATH, 4).add(Aspect.SOUL, 4).add(Aspect.UNDEAD, 6).add(Aspect.GREED, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.WITCH_HAND), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TOOL, 1).add(Aspect.FLESH, 1).add(Aspect.MAGIC, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.ARTHANA), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.GREED, 6).add(Aspect.METAL, 2).add(Aspect.CRYSTAL, 2).add(Aspect.WEAPON, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.HUNTSMANS_SPEAR), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TREE, 3).add(Aspect.MAGIC, 2).add(Aspect.WEAPON, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemMysticUnguent.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENERGY, 2).add(Aspect.MAGIC, 2).add(Aspect.ENTROPY, 10));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBranchEnt.damageValue}, (AspectList)new AspectList().add(Aspect.TREE, 2).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.MYSTIC_BRANCH), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TOOL, 1).add(Aspect.TREE, 2).add(Aspect.MAGIC, 3).add(Aspect.ENTROPY, 10));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.CIRCLE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MECHANISM, 1).add(Aspect.MAGIC, 3).add(Aspect.ORDER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.GLYPH_RITUAL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MECHANISM, 1).add(Aspect.MAGIC, 1).add(Aspect.ORDER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.GLYPH_OTHERWHERE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MECHANISM, 1).add(Aspect.MAGIC, 1).add(Aspect.ORDER, 1).add(Aspect.ELDRITCH, 4).add(Aspect.TRAVEL, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.GLYPH_INFERNAL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MECHANISM, 1).add(Aspect.MAGIC, 1).add(Aspect.ORDER, 1).add(Aspect.FIRE, 2).add(Aspect.TRAVEL, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.DIVINER_WATER), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TOOL, 2).add(Aspect.SENSES, 2).add(Aspect.WATER, 4).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.DIVINER_LAVA), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TOOL, 2).add(Aspect.SENSES, 2).add(Aspect.FIRE, 2).add(Aspect.EARTH, 2).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.TAGLOCK_KIT), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TOOL, 1).add(Aspect.BEAST, 1).add(Aspect.MAN, 1).add(Aspect.LIFE, 1).add(Aspect.ORDER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POPPET), (int[])new int[]{Witchery.Items.POPPET.unboundPoppet.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.PLANT, 2).add(Aspect.SOUL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POPPET), (int[])new int[]{Witchery.Items.POPPET.earthPoppet.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.PLANT, 2).add(Aspect.SOUL, 1).add(Aspect.ARMOR, 1).add(Aspect.EARTH, 1).add(Aspect.FLIGHT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POPPET), (int[])new int[]{Witchery.Items.POPPET.waterPoppet.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.PLANT, 2).add(Aspect.SOUL, 1).add(Aspect.ARMOR, 1).add(Aspect.WATER, 1).add(Aspect.AIR, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POPPET), (int[])new int[]{Witchery.Items.POPPET.firePoppet.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.PLANT, 2).add(Aspect.SOUL, 1).add(Aspect.ARMOR, 1).add(Aspect.FIRE, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POPPET), (int[])new int[]{Witchery.Items.POPPET.foodPoppet.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.PLANT, 2).add(Aspect.SOUL, 1).add(Aspect.ARMOR, 1).add(Aspect.HUNGER, 1).add(Aspect.LIFE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POPPET), (int[])new int[]{Witchery.Items.POPPET.toolPoppet.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.PLANT, 2).add(Aspect.SOUL, 1).add(Aspect.ARMOR, 1).add(Aspect.TOOL, 1).add(Aspect.CRAFT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POPPET), (int[])new int[]{Witchery.Items.POPPET.armorPoppet.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.PLANT, 2).add(Aspect.SOUL, 1).add(Aspect.ARMOR, 2).add(Aspect.CRAFT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POPPET), (int[])new int[]{Witchery.Items.POPPET.deathPoppet.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.PLANT, 2).add(Aspect.SOUL, 1).add(Aspect.ARMOR, 1).add(Aspect.DEATH, 1).add(Aspect.HEAL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POPPET), (int[])new int[]{Witchery.Items.POPPET.antiVoodooPoppet.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.PLANT, 2).add(Aspect.SOUL, 3).add(Aspect.ARMOR, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POPPET), (int[])new int[]{Witchery.Items.POPPET.voodooPoppet.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.PLANT, 2).add(Aspect.SOUL, 4).add(Aspect.MOTION, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POPPET), (int[])new int[]{Witchery.Items.POPPET.vampiricPoppet.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.PLANT, 2).add(Aspect.SOUL, 1).add(Aspect.LIFE, 1).add(Aspect.DEATH, 1).add(Aspect.EXCHANGE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemCandelabra.damageValue}, (AspectList)new AspectList().add(Aspect.METAL, 6).add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 6).add(Aspect.ENERGY, 4).add(Aspect.MAGIC, 2).add(Aspect.LIGHT, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.CANDELABRA), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.METAL, 6).add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 6).add(Aspect.ENERGY, 4).add(Aspect.MAGIC, 2).add(Aspect.LIGHT, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemChaliceEmpty.damageValue}, (AspectList)new AspectList().add(Aspect.METAL, 6).add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 6).add(Aspect.ENERGY, 4).add(Aspect.MAGIC, 2).add(Aspect.VOID, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.CHALICE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.METAL, 6).add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 6).add(Aspect.ENERGY, 4).add(Aspect.MAGIC, 2).add(Aspect.VOID, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemChaliceFull.damageValue}, (AspectList)new AspectList().add(Aspect.METAL, 6).add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 6).add(Aspect.ENERGY, 6).add(Aspect.MAGIC, 4).add(Aspect.VOID, 2).add(Aspect.WATER, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDreamMove.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 1).add(Aspect.SENSES, 1).add(Aspect.SOUL, 2).add(Aspect.DARKNESS, 1).add(Aspect.MOTION, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDreamDig.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 1).add(Aspect.SENSES, 1).add(Aspect.SOUL, 2).add(Aspect.DARKNESS, 1).add(Aspect.ENERGY, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDreamEat.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 1).add(Aspect.SENSES, 1).add(Aspect.SOUL, 2).add(Aspect.DARKNESS, 1).add(Aspect.HUNGER, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDreamIntensity.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 1).add(Aspect.SENSES, 1).add(Aspect.SOUL, 2).add(Aspect.DARKNESS, 1).add(Aspect.MIND, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDreamNightmare.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 1).add(Aspect.SENSES, 1).add(Aspect.SOUL, 2).add(Aspect.DARKNESS, 4).add(Aspect.EXCHANGE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Block)Witchery.Blocks.DREAM_CATCHER), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.AIR, 1).add(Aspect.SENSES, 1).add(Aspect.SOUL, 2).add(Aspect.DARKNESS, 1).add(Aspect.ENERGY, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBoneNeedle.damageValue}, (AspectList)new AspectList().add(Aspect.WEAPON, 1).add(Aspect.FLESH, 1).add(Aspect.DEATH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBroom.damageValue}, (AspectList)new AspectList().add(Aspect.TOOL, 1).add(Aspect.TREE, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBroomEnchanted.damageValue}, (AspectList)new AspectList().add(Aspect.TOOL, 1).add(Aspect.TREE, 2).add(Aspect.MAGIC, 2).add(Aspect.FLIGHT, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemAttunedStone.damageValue}, (AspectList)new AspectList().add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 4).add(Aspect.ENERGY, 4).add(Aspect.MAGIC, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemAttunedStoneCharged.damageValue}, (AspectList)new AspectList().add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 4).add(Aspect.ENERGY, 6).add(Aspect.MAGIC, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemWaystone.damageValue}, (AspectList)new AspectList().add(Aspect.EARTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemWaystoneBound.damageValue}, (AspectList)new AspectList().add(Aspect.EARTH, 1).add(Aspect.ELDRITCH, 2).add(Aspect.MAGIC, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemWaystonePlayerBound.damageValue}, (AspectList)new AspectList().add(Aspect.EARTH, 1).add(Aspect.ELDRITCH, 2).add(Aspect.MAGIC, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemMutandis.damageValue}, (AspectList)new AspectList().add(Aspect.EXCHANGE, 4).add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemMutandisExtremis.damageValue}, (AspectList)new AspectList().add(Aspect.EXCHANGE, 8).add(Aspect.PLANT, 1).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemQuicklime.damageValue}, (AspectList)new AspectList().add(Aspect.WEAPON, 1).add(Aspect.ENTROPY, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemGypsum.damageValue}, (AspectList)new AspectList().add(Aspect.EARTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemAshWood.damageValue}, (AspectList)new AspectList().add(Aspect.TREE, 1).add(Aspect.FIRE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBelladonnaFlower.damageValue}, (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.POISON, 4).add(Aspect.DEATH, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemMandrakeRoot.damageValue}, (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.MAN, 1).add(Aspect.EARTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemIcyNeedle.damageValue}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.COLD, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDemonHeart.damageValue}, (AspectList)new AspectList().add(Aspect.FIRE, 4).add(Aspect.VOID, 2).add(Aspect.FLESH, 2).add(Aspect.SOUL, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemCreeperHeart.damageValue}, (AspectList)new AspectList().add(Aspect.BEAST, 4).add(Aspect.FIRE, 1).add(Aspect.FLESH, 2).add(Aspect.SOUL, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemFrozenHeart.damageValue}, (AspectList)new AspectList().add(Aspect.BEAST, 4).add(Aspect.FIRE, 1).add(Aspect.FLESH, 2).add(Aspect.SOUL, 4).add(Aspect.COLD, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBatWool.damageValue}, (AspectList)new AspectList().add(Aspect.FLESH, 1).add(Aspect.FLIGHT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDogTongue.damageValue}, (AspectList)new AspectList().add(Aspect.FLESH, 1).add(Aspect.BEAST, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemSoftClayJar.damageValue}, (AspectList)new AspectList().add(Aspect.EARTH, 1).add(Aspect.WATER, 1).add(Aspect.VOID, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemEmptyClayJar.damageValue}, (AspectList)new AspectList().add(Aspect.EARTH, 1).add(Aspect.FIRE, 1).add(Aspect.VOID, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemFoulFume.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 3).add(Aspect.EARTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDiamondVapour.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 3).add(Aspect.CRYSTAL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemExhaleOfTheHornedOne.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 3).add(Aspect.FIRE, 1).add(Aspect.UNDEAD, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBreathOfTheGoddess.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 3).add(Aspect.ORDER, 1).add(Aspect.SOUL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemHintOfRebirth.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 3).add(Aspect.LIFE, 1).add(Aspect.EXCHANGE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemReekOfMisfortune.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 3).add(Aspect.ENTROPY, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemWhiffOfMagic.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 3).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemReekOfMisfortune.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 3).add(Aspect.ENTROPY, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemOdourOfPurity.damageValue}, (AspectList)new AspectList().add(Aspect.AIR, 3).add(Aspect.ORDER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemEnderDew.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ELDRITCH, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemOilOfVitriol.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENTROPY, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemTearOfTheGoddess.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ORDER, 1).add(Aspect.SOUL, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemRefinedEvil.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.MIND, 2).add(Aspect.ENTROPY, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDropOfLuck.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENTROPY, 1).add(Aspect.ORDER, 1).add(Aspect.VOID, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemRedstoneSoup.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENERGY, 2).add(Aspect.MAGIC, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemFlyingOintment.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENERGY, 2).add(Aspect.MAGIC, 2).add(Aspect.FLIGHT, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemGhostOfTheLight.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENERGY, 2).add(Aspect.MAGIC, 6).add(Aspect.LIGHT, 15).add(Aspect.ARMOR, 5));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemSoulOfTheWorld.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENERGY, 2).add(Aspect.MAGIC, 2).add(Aspect.EARTH, 10).add(Aspect.METAL, 10));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemSpiritOfOtherwhere.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENERGY, 2).add(Aspect.MAGIC, 2).add(Aspect.ELDRITCH, 20));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemInfernalAnimus.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENERGY, 2).add(Aspect.MAGIC, 2).add(Aspect.DEATH, 5).add(Aspect.UNDEAD, 5).add(Aspect.BEAST, 5).add(Aspect.HUNGER, 5));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBookOven.damageValue}, (AspectList)new AspectList().add(Aspect.MIND, 5).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBookDistilling.damageValue}, (AspectList)new AspectList().add(Aspect.MIND, 5).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBookCircleMagic.damageValue}, (AspectList)new AspectList().add(Aspect.MIND, 5).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBookWands.damageValue}, (AspectList)new AspectList().add(Aspect.MIND, 4).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBookBiomes.damageValue}, (AspectList)new AspectList().add(Aspect.MIND, 4).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBookInfusions.damageValue}, (AspectList)new AspectList().add(Aspect.MIND, 5).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBookHerbology.damageValue}, (AspectList)new AspectList().add(Aspect.MIND, 5).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemOddPorkRaw.damageValue}, (AspectList)new AspectList().add(Aspect.MAN, 1).add(Aspect.HUNGER, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemOddPorkCooked.damageValue}, (AspectList)new AspectList().add(Aspect.MAN, 1).add(Aspect.HUNGER, 2).add(Aspect.FIRE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemRock.damageValue}, (AspectList)new AspectList().add(Aspect.EARTH, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemWeb.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 2).add(Aspect.TRAP, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfVines.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.PLANT, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfIce.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.COLD, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfLove.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.LIFE, 2).add(Aspect.SOUL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfWebs.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.TRAP, 2).add(Aspect.CLOTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfFlowingSpirit.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.SOUL, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfWasting.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.HUNGER, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfCursedLeaping.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.MOTION, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfFrogsTongue.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.MOTION, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfHitchcock.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.BEAST, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfInfection.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.POISON, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemOwletsWing.damageValue}, (AspectList)new AspectList().add(Aspect.BEAST, 1).add(Aspect.AIR, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemToeOfFrog.damageValue}, (AspectList)new AspectList().add(Aspect.BEAST, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemInfernalBlood.damageValue}, (AspectList)new AspectList().add(Aspect.FIRE, 1).add(Aspect.FLESH, 1).add(Aspect.SOUL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemWormyApple.damageValue}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.POISON, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemSleepingApple.damageValue}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.HUNGER, 1).add(Aspect.MIND, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfSleeping.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.MIND, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemTormentedTwine.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 1).add(Aspect.DARKNESS, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemFancifulThread.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 1).add(Aspect.LIGHT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemGoldenThread.damageValue}, (AspectList)new AspectList().add(Aspect.METAL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDisturbedCotton.damageValue}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.DARKNESS, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemMellifluousHunger.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.HUNGER, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemCharmOfDisruptedDreams.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 1).add(Aspect.ENTROPY, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemKobolditeDust.damageValue}, (AspectList)new AspectList().add(Aspect.METAL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemKobolditeNugget.damageValue}, (AspectList)new AspectList().add(Aspect.METAL, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemKobolditeIngot.damageValue}, (AspectList)new AspectList().add(Aspect.METAL, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemKobolditePentacle.damageValue}, (AspectList)new AspectList().add(Aspect.METAL, 4).add(Aspect.MAGIC, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.KOBOLDITE_PICKAXE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.METAL, 3).add(Aspect.MAGIC, 1).add(Aspect.MINE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.WISPY_COTTON), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.LIGHT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.FLOWING_SPIRIT), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.SOUL, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.BUCKET_FLOWINGSPIRIT), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.SOUL, 2).add(Aspect.METAL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.PARASYTIC_LOUSE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.EXCHANGE, 1).add(Aspect.MOTION, 1).add(Aspect.BEAST, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{0}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.TRAP, 2).add(Aspect.CLOTH, 1).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{4}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.TRAP, 2).add(Aspect.CLOTH, 1).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{8}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.TRAP, 2).add(Aspect.CLOTH, 1).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfInk.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.DARKNESS, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{1}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.DARKNESS, 2).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{5}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.DARKNESS, 2).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{9}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.DARKNESS, 2).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfSprouting.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.TREE, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{3}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.TREE, 4).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{7}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.TREE, 4).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{11}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.TREE, 4).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfErosion.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 5).add(Aspect.MINE, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfThorns.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 2).add(Aspect.PLANT, 1).add(Aspect.WEAPON, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{2}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 2).add(Aspect.PLANT, 1).add(Aspect.WEAPON, 1).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{6}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 2).add(Aspect.PLANT, 1).add(Aspect.WEAPON, 1).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.TRAPPED_PLANT), (int[])new int[]{10}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 2).add(Aspect.PLANT, 1).add(Aspect.WEAPON, 1).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemSpectralDust.damageValue}, (AspectList)new AspectList().add(Aspect.SOUL, 2).add(Aspect.UNDEAD, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfRaising.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENTROPY, 1).add(Aspect.UNDEAD, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemNecroStone.damageValue}, (AspectList)new AspectList().add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 4).add(Aspect.ENERGY, 2).add(Aspect.MAGIC, 5).add(Aspect.UNDEAD, 5));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemArtichoke.damageValue}, (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.WATER, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewGrotesque.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.SENSES, 2).add(Aspect.EXCHANGE, 2).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemImpregnatedLeather.damageValue}, (AspectList)new AspectList().add(Aspect.CLOTH, 2).add(Aspect.BEAST, 1).add(Aspect.ARMOR, 1).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.OVEN_FUMEFUNNEL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.VOID, 4).add(Aspect.METAL, 20).add(Aspect.SENSES, 3).add(Aspect.LIGHT, 5).add(Aspect.ORDER, 4).add(Aspect.FIRE, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemFumeFilter.damageValue}, (AspectList)new AspectList().add(Aspect.METAL, 4).add(Aspect.CRYSTAL, 10).add(Aspect.GREED, 4).add(Aspect.ENERGY, 6).add(Aspect.MAGIC, 10).add(Aspect.ORDER, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.OVEN_FUMEFUNNEL_FILTERED), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.METAL, 24).add(Aspect.CRYSTAL, 10).add(Aspect.GREED, 4).add(Aspect.ENERGY, 6).add(Aspect.MAGIC, 10).add(Aspect.ORDER, 8).add(Aspect.VOID, 4).add(Aspect.SENSES, 3).add(Aspect.LIGHT, 5).add(Aspect.FIRE, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.POLYNESIA_CHARM), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MIND, 2).add(Aspect.SENSES, 2).add(Aspect.BEAST, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.DEVILS_TONGUE_CHARM), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MIND, 4).add(Aspect.SENSES, 3).add(Aspect.FIRE, 6).add(Aspect.SOUL, 4).add(Aspect.FLESH, 5));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.WITCH_HAT), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 6).add(Aspect.BEAST, 5).add(Aspect.ARMOR, 5).add(Aspect.MAGIC, 5));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.BABAS_HAT), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 4).add(Aspect.BEAST, 2).add(Aspect.ARMOR, 5).add(Aspect.MAGIC, 5).add(Aspect.ELDRITCH, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.MOGS_QUIVER), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 3).add(Aspect.BEAST, 2).add(Aspect.ARMOR, 1).add(Aspect.MAGIC, 3).add(Aspect.MECHANISM, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.GULGS_GURDLE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 3).add(Aspect.BEAST, 2).add(Aspect.ARMOR, 1).add(Aspect.MAGIC, 3).add(Aspect.WEAPON, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.WITCH_ROBES), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 6).add(Aspect.BEAST, 4).add(Aspect.ARMOR, 5).add(Aspect.MAGIC, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.NECROMANCERS_ROBES), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 6).add(Aspect.BEAST, 4).add(Aspect.ARMOR, 5).add(Aspect.MAGIC, 3).add(Aspect.UNDEAD, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.ICY_SLIPPERS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 2).add(Aspect.BEAST, 2).add(Aspect.ARMOR, 3).add(Aspect.MAGIC, 2).add(Aspect.COLD, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.RUBY_SLIPPERS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 2).add(Aspect.BEAST, 2).add(Aspect.ARMOR, 3).add(Aspect.MAGIC, 2).add(Aspect.ELDRITCH, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.SEEPING_SHOES), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 2).add(Aspect.BEAST, 2).add(Aspect.ARMOR, 3).add(Aspect.MAGIC, 2).add(Aspect.POISON, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.BARK_BELT), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 3).add(Aspect.BEAST, 2).add(Aspect.ARMOR, 6).add(Aspect.MAGIC, 2).add(Aspect.TREE, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemPurifiedMilk.damageValue}, (AspectList)new AspectList().add(Aspect.HEAL, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBatBall.damageValue}, (AspectList)new AspectList().add(Aspect.BEAST, 1).add(Aspect.MOTION, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfBats.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.MOTION, 1).add(Aspect.BEAST, 1).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.BITING_BELT), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 3).add(Aspect.BEAST, 2).add(Aspect.ARMOR, 4).add(Aspect.MAGIC, 1).add(Aspect.HUNGER, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.BREW_BAG), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 2).add(Aspect.BEAST, 2).add(Aspect.VOID, 2).add(Aspect.MECHANISM, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.MUTATING_SPRIG), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TOOL, 2).add(Aspect.EXCHANGE, 8).add(Aspect.MAGIC, 1).add(Aspect.TREE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDoorKey.damageValue}, (AspectList)new AspectList().add(Aspect.MECHANISM, 1).add(Aspect.TOOL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemDoorKeyring.damageValue}, (AspectList)new AspectList().add(Aspect.MECHANISM, 1).add(Aspect.TOOL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.BARRIER), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MAGIC, 2).add(Aspect.ARMOR, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.VOID_BRAMBLE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.ORDER, 4).add(Aspect.ELDRITCH, 3).add(Aspect.ARMOR, 4).add(Aspect.MAGIC, 4).add(Aspect.WATER, 1).add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.CHALK_GOLDEN), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TOOL, 1).add(Aspect.MAGIC, 3).add(Aspect.ORDER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.CHALK_RITUAL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TOOL, 1).add(Aspect.MAGIC, 1).add(Aspect.ORDER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.CHALK_OTHERWHERE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TOOL, 1).add(Aspect.MAGIC, 1).add(Aspect.ORDER, 1).add(Aspect.ELDRITCH, 4).add(Aspect.TRAVEL, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.CHALK_INFERNAL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TOOL, 1).add(Aspect.MAGIC, 1).add(Aspect.ENTROPY, 1).add(Aspect.FIRE, 4).add(Aspect.BEAST, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.CIRCLE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MECHANISM, 1).add(Aspect.MAGIC, 3).add(Aspect.ORDER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.GLYPH_RITUAL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MECHANISM, 1).add(Aspect.MAGIC, 1).add(Aspect.ORDER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.GLYPH_OTHERWHERE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MECHANISM, 1).add(Aspect.MAGIC, 1).add(Aspect.ORDER, 1).add(Aspect.ELDRITCH, 4).add(Aspect.TRAVEL, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.GLYPH_INFERNAL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MECHANISM, 1).add(Aspect.MAGIC, 1).add(Aspect.ENTROPY, 1).add(Aspect.FIRE, 4).add(Aspect.BEAST, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.CIRCLE_TALISMAN), (int[])new int[]{0}, (AspectList)new AspectList().add(Aspect.TOOL, 2).add(Aspect.CRYSTAL, 4).add(Aspect.METAL, 8).add(Aspect.MAGIC, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.LEECH_CHEST), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.VOID, 3).add(Aspect.HUNGER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.STATUE_GODDESS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.EARTH, 10).add(Aspect.MAGIC, 10).add(Aspect.HEAL, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.CRITTER_SNARE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.PLANT, 1).add(Aspect.TRAP, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.BRAMBLE), (int[])new int[]{0}, (AspectList)new AspectList().add(Aspect.ORDER, 2).add(Aspect.ELDRITCH, 3).add(Aspect.WATER, 1).add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.BRAMBLE), (int[])new int[]{1}, (AspectList)new AspectList().add(Aspect.WEAPON, 1).add(Aspect.WATER, 1).add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.GRASSPER), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.PLANT, 1).add(Aspect.VOID, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemQuartzSphere.damageValue}, (AspectList)new AspectList().add(Aspect.CRYSTAL, 1).add(Aspect.EARTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemHappenstanceOil.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENERGY, 2).add(Aspect.MAGIC, 2).add(Aspect.SENSES, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemSeerStone.damageValue}, (AspectList)new AspectList().add(Aspect.CRYSTAL, 1).add(Aspect.EARTH, 1).add(Aspect.SENSES, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.CRYSTAL_BALL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CRYSTAL, 2).add(Aspect.MAGIC, 2).add(Aspect.SENSES, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.BLOOD_ROSE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.HUNGER, 1).add(Aspect.MECHANISM, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.DEMON_HEART), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.FIRE, 4).add(Aspect.VOID, 2).add(Aspect.FLESH, 2).add(Aspect.SOUL, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemGraveyardDust.damageValue}, (AspectList)new AspectList().add(Aspect.SOUL, 2).add(Aspect.UNDEAD, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBookBurning.damageValue}, (AspectList)new AspectList().add(Aspect.MIND, 4).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.FETISH_WITCHS_LADDER), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TRAP, 1).add(Aspect.AIR, 1).add(Aspect.MECHANISM, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.FETISH_TREANT_IDOL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TRAP, 1).add(Aspect.TREE, 2).add(Aspect.MECHANISM, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.FETISH_SCARECROW), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TRAP, 1).add(Aspect.CLOTH, 2).add(Aspect.MECHANISM, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.BOLINE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WEAPON, 1).add(Aspect.METAL, 1).add(Aspect.CRYSTAL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.SPECTRAL_STONE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CRYSTAL, 3).add(Aspect.TRAP, 4));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.BRAZIER), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MECHANISM, 2).add(Aspect.FIRE, 2).add(Aspect.METAL, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemCongealedSpirit.damageValue}, (AspectList)new AspectList().add(Aspect.SOUL, 6));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.SEEDS_WORMWOOD), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_WORMWOOD), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.UNDEAD, 2).add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemWormwood.damageValue}, (AspectList)new AspectList().add(Aspect.UNDEAD, 2).add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemSubduedSpirit.damageValue}, (AspectList)new AspectList().add(Aspect.SOUL, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemFocusedWill.damageValue}, (AspectList)new AspectList().add(Aspect.SOUL, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemCondensedFear.damageValue}, (AspectList)new AspectList().add(Aspect.DEATH, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfSolidRock.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.EXCHANGE, 1).add(Aspect.EARTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfSolidDirt.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.EXCHANGE, 1).add(Aspect.EARTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfSolidSand.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.EXCHANGE, 1).add(Aspect.EARTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfSolidSandstone.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.EXCHANGE, 1).add(Aspect.EARTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfSolidErosion.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 3).add(Aspect.EXCHANGE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemInfusionBase.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ORDER, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfSoaring.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.AIR, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewGrave.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.UNDEAD, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewRevealing.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.SENSES, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewSubstitution.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.EXCHANGE, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewOfHollowTears.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1).add(Aspect.VOID, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.HOLLOW_TEARS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.VOID, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.BUCKET_HOLLOWTEARS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.VOID, 2).add(Aspect.METAL, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemNullCatalyst.damageValue}, (AspectList)new AspectList().add(Aspect.ENTROPY, 1).add(Aspect.VOID, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemNullifiedLeather.damageValue}, (AspectList)new AspectList().add(Aspect.VOID, 2).add(Aspect.CLOTH, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBoltStake.damageValue}, (AspectList)new AspectList().add(Aspect.WEAPON, 1).add(Aspect.TREE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBoltSplitting.damageValue}, (AspectList)new AspectList().add(Aspect.WEAPON, 1).add(Aspect.TREE, 1).add(Aspect.ENTROPY, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBoltHoly.damageValue}, (AspectList)new AspectList().add(Aspect.WEAPON, 1).add(Aspect.DEATH, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBoltAntiMagic.damageValue}, (AspectList)new AspectList().add(Aspect.WEAPON, 1).add(Aspect.DEATH, 1).add(Aspect.MAGIC, 2).add(Aspect.VOID, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.DEATH_HOOD), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 1).add(Aspect.DEATH, 4).add(Aspect.ARMOR, 2).add(Aspect.TRAP, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.DEATH_ROBE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 1).add(Aspect.DEATH, 4).add(Aspect.ARMOR, 2).add(Aspect.FIRE, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.DEATH_FEET), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.CLOTH, 1).add(Aspect.DEATH, 4).add(Aspect.ARMOR, 2).add(Aspect.WATER, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.DEATH_HAND), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WEAPON, 3).add(Aspect.DEATH, 4).add(Aspect.SOUL, 3));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBinkyHead.damageValue}, (AspectList)new AspectList().add(Aspect.DEATH, 3).add(Aspect.BEAST, 2).add(Aspect.EXCHANGE, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.HUNTER_HAT), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.ARMOR, 1).add(Aspect.CLOTH, 1).add(Aspect.VOID, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.HUNTER_BOOTS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.ARMOR, 1).add(Aspect.CLOTH, 1).add(Aspect.VOID, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.HUNTER_LEGS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.ARMOR, 1).add(Aspect.CLOTH, 1).add(Aspect.VOID, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.HUNTER_COAT), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.ARMOR, 1).add(Aspect.CLOTH, 1).add(Aspect.VOID, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.CROSSBOW_PISTOL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WEAPON, 2).add(Aspect.MOTION, 1).add(Aspect.MECHANISM, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.SHELF_COMPASS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.SENSES, 2).add(Aspect.CRYSTAL, 3).add(Aspect.MAGIC, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.POTIONS), (int[])new int[]{Witchery.Items.POTIONS.potionAntidote.damageValue}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.HEAL, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.SEEDS_MINDRAKE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WATER, 1).add(Aspect.EXCHANGE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Block)Witchery.Blocks.CROP_MINDRAKE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.MAN, 1).add(Aspect.CROP, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.PLAYER_COMPASS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.SENSES, 2).add(Aspect.MAN, 1).add(Aspect.MAGIC, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.EARMUFFS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.SENSES, 1).add(Aspect.CLOTH, 1).add(Aspect.BEAST, 1).add(Aspect.ARMOR, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.PIT_DIRT), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.EARTH, 1).add(Aspect.TRAP, 2).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.PIT_GRASS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.EARTH, 1).add(Aspect.TRAP, 2).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.VINE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.LILY), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.CACTUS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.TRAP, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.WEB), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.TRAP, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.SNOW_STAIRS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.SNOW_SLAB_SINGLE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.SNOW_SLAB_DOUBLE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.SNOW_PRESSURE_PLATE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1).add(Aspect.MECHANISM, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.PERPETUAL_ICE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.PERPETUAL_ICE_STAIRS), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.PERPETUAL_ICE_SLAB_SINGLE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.PERPETUAL_ICE_SLAB_DOUBLE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.PERPETUAL_ICE_FENCE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.PERPETUAL_ICE_FENCE_GATE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1).add(Aspect.MECHANISM, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.PERPETUAL_ICE_DOOR), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1).add(Aspect.MECHANISM, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.STOCKADE_ICE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1).add(Aspect.ARMOR, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.PERPETUAL_ICE_PRESSURE_PLATE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.COLD, 1).add(Aspect.WATER, 1).add(Aspect.MECHANISM, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Blocks.VINE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.BIOME_BOOK), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MIND, 5).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.BIOME_NOTE), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MIND, 2).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.CAULDRON_BOOK), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.MIND, 5).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.BREW_FUEL), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.ENERGY, 2).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.BREW_ENDLESS_WATER), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WATER, 8).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemAnnointingPaste.damageValue}, (AspectList)new AspectList().add(Aspect.PLANT, 1).add(Aspect.EXCHANGE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack(Witchery.Items.BREW), (int[])new int[]{-1}, (AspectList)new AspectList().add(Aspect.WATER, 2).add(Aspect.MAGIC, 3));
            ThaumcraftApi.registerEntityTag((String)"witchery.mindrake", (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.MAN, 1).add(Aspect.SENSES, 1).add(Aspect.MOTION, 1).add(Aspect.FIRE, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.demon", (AspectList)new AspectList().add(Aspect.DEATH, 5).add(Aspect.VOID, 2).add(Aspect.FIRE, 4).add(Aspect.MAGIC, 6).add(Aspect.MOTION, 2).add(Aspect.SENSES, 2).add(Aspect.GREED, 8).add(Aspect.BEAST, 2).add(Aspect.ENTROPY, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.familiar", (AspectList)new AspectList().add(Aspect.AIR, 5).add(Aspect.SOUL, 6).add(Aspect.MAGIC, 2).add(Aspect.VOID, 2).add(Aspect.MOTION, 1).add(Aspect.BEAST, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.mandrake", (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.MAN, 1).add(Aspect.AIR, 2).add(Aspect.SENSES, 2).add(Aspect.MOTION, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.treefyd", (AspectList)new AspectList().add(Aspect.PLANT, 4).add(Aspect.MAGIC, 2).add(Aspect.MOTION, 2).add(Aspect.MIND, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.hornedHuntsman", (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.MAGIC, 4).add(Aspect.MOTION, 2).add(Aspect.MIND, 4).add(Aspect.BEAST, 8).add(Aspect.EARTH, 2).add(Aspect.SOUL, 4), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.ent", (AspectList)new AspectList().add(Aspect.PLANT, 2).add(Aspect.TREE, 8).add(Aspect.MAGIC, 2).add(Aspect.MOTION, 2).add(Aspect.MIND, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.babayaga", (AspectList)new AspectList().add(Aspect.MAN, 2).add(Aspect.MAGIC, 6).add(Aspect.MOTION, 2).add(Aspect.MIND, 4).add(Aspect.SOUL, 8), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.owl", (AspectList)new AspectList().add(Aspect.FLIGHT, 2).add(Aspect.MOTION, 2).add(Aspect.MIND, 1).add(Aspect.BEAST, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.toad", (AspectList)new AspectList().add(Aspect.SLIME, 1).add(Aspect.WATER, 1).add(Aspect.MOTION, 2).add(Aspect.BEAST, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.cat", (AspectList)new AspectList().add(Aspect.SENSES, 2).add(Aspect.MIND, 1).add(Aspect.MOTION, 2).add(Aspect.BEAST, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.louse", (AspectList)new AspectList().add(Aspect.EXCHANGE, 1).add(Aspect.MOTION, 1).add(Aspect.BEAST, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.illusionSpider", (AspectList)new AspectList().add(Aspect.AIR, 2).add(Aspect.SENSES, 1).add(Aspect.MOTION, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.illusionCreeper", (AspectList)new AspectList().add(Aspect.AIR, 2).add(Aspect.SENSES, 1).add(Aspect.MOTION, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.illusionZombie", (AspectList)new AspectList().add(Aspect.AIR, 2).add(Aspect.SENSES, 1).add(Aspect.MOTION, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.covenwitch", (AspectList)new AspectList().add(Aspect.MAN, 2).add(Aspect.MAGIC, 3).add(Aspect.MIND, 2).add(Aspect.SOUL, 1).add(Aspect.MOTION, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.witchhunter", (AspectList)new AspectList().add(Aspect.MAN, 2).add(Aspect.MIND, 2).add(Aspect.SOUL, 1).add(Aspect.MOTION, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.corpse", (AspectList)new AspectList().add(Aspect.MAN, 2).add(Aspect.MIND, 2).add(Aspect.SOUL, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.nightmare", (AspectList)new AspectList().add(Aspect.VOID, 3).add(Aspect.MAGIC, 2).add(Aspect.SOUL, 2).add(Aspect.HUNGER, 4), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.spirit", (AspectList)new AspectList().add(Aspect.SOUL, 3).add(Aspect.AIR, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.lostsoul", (AspectList)new AspectList().add(Aspect.SOUL, 3).add(Aspect.AIR, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.spectre", (AspectList)new AspectList().add(Aspect.DEATH, 2).add(Aspect.UNDEAD, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.banshee", (AspectList)new AspectList().add(Aspect.DEATH, 2).add(Aspect.UNDEAD, 1).add(Aspect.SENSES, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.poltergeist", (AspectList)new AspectList().add(Aspect.DEATH, 2).add(Aspect.UNDEAD, 1).add(Aspect.MOTION, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.death", (AspectList)new AspectList().add(Aspect.DEATH, 8).add(Aspect.SOUL, 8), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.imp", (AspectList)new AspectList().add(Aspect.VOID, 2).add(Aspect.FIRE, 3).add(Aspect.MAGIC, 7).add(Aspect.MOTION, 2).add(Aspect.SENSES, 2).add(Aspect.GREED, 6).add(Aspect.BEAST, 2).add(Aspect.ENTROPY, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.lordoftorment", (AspectList)new AspectList().add(Aspect.DEATH, 2).add(Aspect.VOID, 2).add(Aspect.FIRE, 5).add(Aspect.MAGIC, 8).add(Aspect.MOTION, 3).add(Aspect.SENSES, 2).add(Aspect.BEAST, 2).add(Aspect.ENTROPY, 2).add(Aspect.TRAP, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.goblin", (AspectList)new AspectList().add(Aspect.SENSES, 2).add(Aspect.MIND, 1).add(Aspect.MOTION, 2).add(Aspect.MAN, 1), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.goblingulg", (AspectList)new AspectList().add(Aspect.SENSES, 2).add(Aspect.MIND, 1).add(Aspect.MOTION, 2).add(Aspect.MAN, 2).add(Aspect.MAGIC, 3).add(Aspect.ARMOR, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.goblinmog", (AspectList)new AspectList().add(Aspect.SENSES, 2).add(Aspect.MIND, 1).add(Aspect.MOTION, 2).add(Aspect.MAN, 2).add(Aspect.MAGIC, 3).add(Aspect.ARMOR, 2), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerEntityTag((String)"witchery.leonard", (AspectList)new AspectList().add(Aspect.SENSES, 2).add(Aspect.MIND, 1).add(Aspect.MOTION, 2).add(Aspect.MAN, 2).add(Aspect.MAGIC, 8), (ThaumcraftApi.EntityTagsNBT[])new ThaumcraftApi.EntityTagsNBT[0]);
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewSoulAnguish.damageValue}, (AspectList)new AspectList().add(Aspect.SOUL, 2).add(Aspect.MIND, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewSoulFear.damageValue}, (AspectList)new AspectList().add(Aspect.SOUL, 2).add(Aspect.SENSES, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewSoulHunger.damageValue}, (AspectList)new AspectList().add(Aspect.SOUL, 2).add(Aspect.HUNGER, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemBrewSoulTorment.damageValue}, (AspectList)new AspectList().add(Aspect.SOUL, 2).add(Aspect.TRAP, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemContractOwnership.damageValue}, (AspectList)new AspectList().add(Aspect.EXCHANGE, 2).add(Aspect.SOUL, 2));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemContractBlaze.damageValue}, (AspectList)new AspectList().add(Aspect.EXCHANGE, 2).add(Aspect.FIRE, 1).add(Aspect.BEAST, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemContractEvaporate.damageValue}, (AspectList)new AspectList().add(Aspect.EXCHANGE, 2).add(Aspect.FIRE, 1).add(Aspect.WATER, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemContractFieryTouch.damageValue}, (AspectList)new AspectList().add(Aspect.EXCHANGE, 2).add(Aspect.FIRE, 1).add(Aspect.MECHANISM, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemContractResistFire.damageValue}, (AspectList)new AspectList().add(Aspect.EXCHANGE, 2).add(Aspect.FIRE, 1).add(Aspect.ARMOR, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemContractSmelting.damageValue}, (AspectList)new AspectList().add(Aspect.EXCHANGE, 2).add(Aspect.FIRE, 1).add(Aspect.MINE, 1));
            ThaumcraftApi.registerObjectTag((ItemStack)new ItemStack((Item)Witchery.Items.GENERIC), (int[])new int[]{Witchery.Items.GENERIC.itemContractTorment.damageValue}, (AspectList)new AspectList().add(Aspect.EXCHANGE, 2).add(Aspect.TRAP, 3));
        }
    }
}

